"""Formula and fact flashcards for the recall drill (facts.html). There is no formula booklet in the
TMUA, so every one of these must be recalled from memory. (topic slug, prompt, answer, spec ref)"""
from gen.model import Fact as F

FACTS = [
    # indices & surds
    F("indices-surds", r"$a^{m/n}$ equals?", r"$\left(\sqrt[n]{a}\right)^m = \sqrt[n]{a^m}$", "MM1.1"),
    F("indices-surds", r"$a^{-n}$ equals?", r"$\dfrac{1}{a^n}$", "MM1.1"),
    F("indices-surds", r"Rationalise $\dfrac{1}{a + \sqrt b}$", r"Multiply top and bottom by $a - \sqrt b$: $\dfrac{a - \sqrt b}{a^2 - b}$", "MM1.2"),
    F("indices-surds", r"$\sqrt{x^2}$ equals?", r"$|x|$ (the square root symbol always means the non-negative root)", "MM1.7"),
    # quadratics
    F("quadratics", r"The quadratic formula", r"$x = \dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a}$", "MM1.3"),
    F("quadratics", r"Discriminant conditions for $0$, $1$, $2$ real roots", r"$b^2 - 4ac < 0$: none; $= 0$: one repeated; $> 0$: two distinct", "MM1.3"),
    F("quadratics", r"Complete the square: $x^2 + bx + c$", r"$\left(x + \dfrac b2\right)^2 + c - \dfrac{b^2}{4}$; vertex at $x = -\frac b2$", "MM1.3"),
    F("quadratics", r"Sum and product of the roots of $ax^2 + bx + c = 0$", r"$\alpha + \beta = -\dfrac ba$, $\quad \alpha\beta = \dfrac ca$", "MM1.3"),
    F("quadratics", r"$\alpha^2 + \beta^2$ in terms of $\alpha + \beta$ and $\alpha\beta$", r"$(\alpha + \beta)^2 - 2\alpha\beta$", "MM1.3"),
    F("quadratics", r"$f(x) = ax^2 + bx + c > 0$ for all $x$ when?", r"$a > 0$ and $b^2 - 4ac < 0$", "MM1.5"),
    # polynomials
    F("polynomials", r"Remainder Theorem", r"The remainder when $f(x)$ is divided by $(ax - b)$ is $f\!\left(\frac ba\right)$", "MM1.6"),
    F("polynomials", r"Factor Theorem", r"$(x - a)$ is a factor of $f(x)$ if and only if $f(a) = 0$", "MM1.6"),
    F("polynomials", r"$a^3 - b^3$ factorised", r"$(a - b)(a^2 + ab + b^2)$", "MM1.6"),
    F("polynomials", r"Sum of the coefficients of a polynomial $f(x)$", r"$f(1)$", "MM1.6"),
    # functions
    F("functions", r"$y = f(x + a)$ is which transformation?", r"Translation by $a$ in the **negative** $x$-direction (left)", "MM8.2"),
    F("functions", r"$y = f(ax)$ is which transformation?", r"Stretch parallel to the $x$-axis with scale factor $\frac1a$", "MM8.2"),
    F("functions", r"$y = af(x)$ and $y = f(x) + a$?", r"Vertical stretch factor $a$; translation $a$ upwards", "MM8.2"),
    F("functions", r"$y = f(-x)$ and $y = -f(x)$?", r"Reflection in the $y$-axis; reflection in the $x$-axis", "MM8.2"),
    F("functions", r"Vertex of $y = a(x + b)^2 + c$", r"$(-b, c)$", "MM8.4"),
    # sequences
    F("sequences-series", r"$n$th term and sum of an arithmetic series", r"$u_n = a + (n-1)d$; $\quad S_n = \frac n2[2a + (n-1)d] = \frac n2(a + l)$", "MM2.2"),
    F("sequences-series", r"$1 + 2 + \cdots + n$", r"$\dfrac{n(n+1)}{2}$", "MM2.2"),
    F("sequences-series", r"$n$th term and sum of a geometric series", r"$u_n = ar^{n-1}$; $\quad S_n = \dfrac{a(r^n - 1)}{r - 1}$", "MM2.3"),
    F("sequences-series", r"Sum to infinity of a geometric series, and the condition", r"$S_\infty = \dfrac{a}{1 - r}$, valid only for $|r| < 1$", "MM2.3"),
    F("sequences-series", r"$p, q, r$ in geometric progression when?", r"$q^2 = pr$", "MM2.3"),
    # binomial
    F("binomial", r"$\binom nr$ formula", r"$\dfrac{n!}{r!(n-r)!}$", "MM2.4"),
    F("binomial", r"General term of $(a + bx)^n$", r"$\binom nr a^{n-r}(bx)^r$", "MM2.4"),
    F("binomial", r"$\sum_{r=0}^{n}\binom nr$ equals?", r"$2^n$", "MM2.4"),
    F("binomial", r"Row 5 of Pascal's triangle", r"$1, 5, 10, 10, 5, 1$", "MM2.4"),
    # lines
    F("straight-lines", r"Gradient condition for perpendicular lines", r"$m_1 m_2 = -1$", "MM3.1"),
    F("straight-lines", r"Gradient of $ax + by + c = 0$", r"$-\dfrac ab$", "MM3.1"),
    F("straight-lines", r"Distance and midpoint of $(x_1,y_1)$, $(x_2,y_2)$", r"$\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$; $\left(\frac{x_1+x_2}{2}, \frac{y_1+y_2}{2}\right)$", "MM3.1"),
    F("straight-lines", r"Distance from $(x_0, y_0)$ to $ax + by + c = 0$", r"$\dfrac{|ax_0 + by_0 + c|}{\sqrt{a^2 + b^2}}$", "MM3.1"),
    # circles
    F("circles", r"Centre and radius of $x^2 + y^2 + cx + dy + e = 0$", r"Centre $\left(-\frac c2, -\frac d2\right)$, $r^2 = \frac{c^2}{4} + \frac{d^2}{4} - e$", "MM3.2"),
    F("circles", r"Length of the tangent from $P$ to a circle with centre $C$, radius $r$", r"$\sqrt{PC^2 - r^2}$", "MM3.2"),
    F("circles", r"Angle at the centre vs angle at the circumference", r"The angle at the centre is twice the angle at the circumference subtended by the same arc", "MM3.3"),
    F("circles", r"Opposite angles of a cyclic quadrilateral", r"Sum to $180^\circ$", "MM3.3"),
    F("circles", r"Alternate segment theorem", r"The angle between a tangent and a chord equals the angle in the alternate segment", "MM3.3"),
    F("circles", r"Two circles touch externally when?", r"Distance between centres $= r_1 + r_2$", "MM3.2"),
    # triangles
    F("trig-triangles", r"Cosine rule", r"$a^2 = b^2 + c^2 - 2bc\cos A$", "MM4.1"),
    F("trig-triangles", r"Sine rule", r"$\dfrac{a}{\sin A} = \dfrac{b}{\sin B} = \dfrac{c}{\sin C}$", "MM4.1"),
    F("trig-triangles", r"Area of a triangle from two sides and the included angle", r"$\frac12 ab\sin C$", "MM4.1"),
    F("trig-triangles", r"Arc length and sector area (radians)", r"$s = r\theta$, $\quad A = \frac12 r^2\theta$", "MM4.2"),
    F("trig-triangles", r"Area of a segment (radians)", r"$\frac12 r^2(\theta - \sin\theta)$", "MM4.2"),
    F("trig-triangles", r"When does the sine rule give two triangles?", r"Given $a$, $b$, $A$ with $b\sin A < a < b$", "MM4.1"),
    # trig functions
    F("trig-functions", r"$\sin 30^\circ$, $\sin 45^\circ$, $\sin 60^\circ$", r"$\frac12$, $\frac{\sqrt2}{2}$, $\frac{\sqrt3}{2}$", "MM4.3"),
    F("trig-functions", r"$\cos 30^\circ$, $\cos 45^\circ$, $\cos 60^\circ$", r"$\frac{\sqrt3}{2}$, $\frac{\sqrt2}{2}$, $\frac12$", "MM4.3"),
    F("trig-functions", r"$\tan 30^\circ$, $\tan 45^\circ$, $\tan 60^\circ$", r"$\frac{1}{\sqrt3}$, $1$, $\sqrt3$", "MM4.3"),
    F("trig-functions", r"The two trig identities in the spec", r"$\tan\theta = \dfrac{\sin\theta}{\cos\theta}$, $\quad \sin^2\theta + \cos^2\theta = 1$", "MM4.5"),
    F("trig-functions", r"Periods of $\sin$, $\cos$, $\tan$", r"$360^\circ$, $360^\circ$, $180^\circ$ ($2\pi$, $2\pi$, $\pi$)", "MM4.4"),
    F("trig-functions", r"Second solution of $\sin x = k$ from the first, $\alpha$", r"$180^\circ - \alpha$", "MM4.6"),
    F("trig-functions", r"Second solution of $\cos x = k$ from the first, $\alpha$", r"$360^\circ - \alpha$ (i.e. $-\alpha$)", "MM4.6"),
    F("trig-functions", r"Period of $y = \sin(kx)$", r"$\dfrac{360^\circ}{k}$", "MM4.4"),
    # logs
    F("exp-logs", r"$\log_a(xy)$, $\log_a\frac xy$, $\log_a x^k$", r"$\log_a x + \log_a y$; $\log_a x - \log_a y$; $k\log_a x$", "MM5.2"),
    F("exp-logs", r"$\log_a a$, $\log_a 1$, $\log_a\frac1x$", r"$1$, $0$, $-\log_a x$", "MM5.2"),
    F("exp-logs", r"$a^b = c$ in log form", r"$b = \log_a c$", "MM5.2"),
    F("exp-logs", r"Graph of $y = \log_a x$ is the reflection of ... in ...", r"$y = a^x$ in the line $y = x$", "MM5.1"),
    # calculus
    F("differentiation", r"$\dfrac{d}{dx}x^n$", r"$nx^{n-1}$", "MM6.2"),
    F("differentiation", r"Gradient of the normal at a point where $f'(x) = m$", r"$-\dfrac1m$", "MM6.3"),
    F("differentiation", r"Second-derivative test", r"$f'' > 0$: minimum; $f'' < 0$: maximum; $f'' = 0$: inconclusive", "MM6.1"),
    F("differentiation", r"Strictly increasing function condition", r"$f'(x) > 0$", "MM6.3"),
    F("integration", r"$\displaystyle\int x^n\,dx$", r"$\dfrac{x^{n+1}}{n+1} + c$ for $n \neq -1$", "MM7.2"),
    F("integration", r"Trapezium rule with $n$ strips of width $h$", r"$\frac h2\left[y_0 + 2(y_1 + \cdots + y_{n-1}) + y_n\right]$", "MM7.5"),
    F("integration", r"When does the trapezium rule overestimate?", r"When the curve is convex (bends upwards) on the interval", "MM7.5"),
    F("integration", r"Fundamental Theorem of Calculus (derivative form)", r"$\dfrac{d}{dx}\displaystyle\int_a^x f(t)\,dt = f(x)$", "MM7.4"),
    F("integration", r"$\displaystyle\int_a^b f + \int_b^c f$", r"$\displaystyle\int_a^c f$", "MM7.4"),
    # GCSE
    F("number", r"Number of divisors of $p^a q^b$", r"$(a+1)(b+1)$", "M2.3"),
    F("number", r"Convert $90$ km/h to m/s", r"$90 \times \frac{1000}{3600} = 25$ m/s", "M1.2"),
    F("number", r"Interval for $x = 4.6$ correct to 1 d.p.", r"$4.55 \leq x < 4.65$", "M2.13"),
    F("ratio-proportion", r"Multiplier for a $p\%$ decrease", r"$1 - \dfrac{p}{100}$", "M3.8"),
    F("ratio-proportion", r"Similar solids with length ratio $k$: area and volume ratios", r"$k^2$ and $k^3$", "M3.10"),
    F("ratio-proportion", r"Compound growth after $n$ periods at rate $r$", r"$P(1 + r)^n$", "M3.11"),
    F("gcse-algebra", r"$n$th term of a linear sequence with first term $a$, difference $d$", r"$dn + (a - d)$", "M4.19"),
    F("gcse-algebra", r"Quadratic sequence: the second difference equals?", r"$2a$ where the $n$th term is $an^2 + bn + c$", "M4.19"),
    F("geometry", r"Sum of the interior angles of an $n$-gon", r"$180(n - 2)^\circ$", "M5.2"),
    F("geometry", r"Exterior angle of a regular $n$-gon", r"$\dfrac{360^\circ}{n}$", "M5.2"),
    F("geometry", r"Congruence criteria", r"SSS, SAS, ASA, RHS (not SSA)", "M5.4"),
    F("geometry", r"Rotation $90^\circ$ anticlockwise about the origin", r"$(x, y) \to (-y, x)$", "M5.6"),
    F("mensuration", r"Diagonal of an $a \times b \times c$ cuboid", r"$\sqrt{a^2 + b^2 + c^2}$", "M5.7"),
    F("mensuration", r"Volume and curved surface area of a cylinder", r"$\pi r^2 h$ and $2\pi r h$", "M5.16"),
    F("mensuration", r"Area of a trapezium", r"$\frac12(a + b)h$", "M5.16"),
    F("mensuration", r"Volume of a cone and of a sphere (given if needed)", r"$\frac13\pi r^2 h$ and $\frac43\pi r^3$", "M5.17"),
    F("statistics", r"Frequency density", r"$\dfrac{\text{frequency}}{\text{class width}}$", "M6.2"),
    F("statistics", r"Effect of $x \to ax + b$ on the mean and the range", r"Mean $\to a\bar x + b$; range $\to |a| \times$ range", "M6.3"),
    F("probability", r"$P(A \text{ or } B)$", r"$P(A) + P(B) - P(A \text{ and } B)$", "M7.5"),
    F("probability", r"Independent events", r"$P(A \text{ and } B) = P(A)P(B)$", "M7.7"),
    F("probability", r"$P(\text{at least one})$", r"$1 - P(\text{none})$", "M7.4"),
    # logic & proof
    F("logic", r"Contrapositive of 'if $A$ then $B$'", r"'If not $B$ then not $A$' - logically equivalent to the original", "Arg1"),
    F("logic", r"Converse of 'if $A$ then $B$'", r"'If $B$ then $A$' - not equivalent to the original", "Arg1"),
    F("logic", r"'$A$ only if $B$' means?", r"$A \Rightarrow B$", "Arg1"),
    F("logic", r"$P$ is sufficient for $Q$ means? necessary?", r"Sufficient: $P \Rightarrow Q$. Necessary: $Q \Rightarrow P$", "Arg2"),
    F("logic", r"Negation of 'for all $x$, $P(x)$'", r"'There exists $x$ such that not $P(x)$'", "Arg4"),
    F("logic", r"Negation of '$A$ and $B$'", r"'(not $A$) or (not $B$)'", "Arg4"),
    F("logic", r"'$A \Rightarrow B$' is equivalent to which 'or' statement?", r"'(not $A$) or $B$'", "Arg1"),
    F("proof", r"What does a counterexample need?", r"Hypothesis true and conclusion false", "Prf1"),
    F("proof", r"Proof by contradiction: what do you assume?", r"That the hypothesis holds and the conclusion is false", "Prf1"),
    F("errors", r"$x^2 = y^2$ implies?", r"$x = y$ or $x = -y$", "Err2"),
    F("errors", r"$\sin\alpha = \sin\beta$ implies?", r"$\alpha = \beta + 360^\circ k$ or $\alpha = 180^\circ - \beta + 360^\circ k$", "Err2"),
    F("errors", r"Multiplying an inequality by a negative number", r"Reverses the inequality sign", "Err2"),
    F("reasoning", r"Pigeonhole principle", r"If $n + 1$ objects go into $n$ boxes, some box holds at least two", "Prf5"),
    F("reasoning", r"Inclusion-exclusion for two sets", r"$|A \cup B| = |A| + |B| - |A \cap B|$", "Prf5"),
]
