"""Which topic each question in the published TMUA papers covers, with a few words of description.
Used for the 'real questions by topic' index, the per-topic 'how it has been examined' lists and the
per-topic breakdown when a real paper is marked online.

OFFICIAL_INDEX[series][paper][question] = (topic slug, short description)
"""

OFFICIAL_INDEX = {
    "2023": {
        1: {1: ("integration", "definite integrals of ax + b fix a and b"), 2: ("quadratics", "line and parabola do not meet: range of m"),
            3: ("integration", "combining integrals over adjacent ranges"), 4: ("trig-functions", "sum of sines"),
            5: ("geometry", "shape with two lines of symmetry"), 6: ("binomial", "coefficients of (2 + 3x)^12 divisible by 12"),
            7: ("polynomials", "polynomials P(x) and Q(x)"), 8: ("trig-triangles", "'fun' triangles: sine rule ambiguous case"),
            9: ("trig-functions", "count solutions of (1 + 3cos 3x)^2 = 4"), 10: ("integration", "trapezium rule error for sqrt(4 - x^2)"),
            11: ("functions", "f(kx) and f(x - c) with the same minimum"), 12: ("trig-functions", "solutions of 2tan^2 x sin 2x = 1"),
            13: ("circles", "maximum distance between points on two circles"), 14: ("differentiation", "cubic with three distinct real roots"),
            15: ("trig-functions", "max minus min of a cos x"), 16: ("straight-lines", "right-angled triangle from coordinates"),
            17: ("circles", "family of circles x^2 + y^2 = 2n(x + y)"), 18: ("sequences-series", "geometric series in k"),
            19: ("integration", "dy/dx = |-6x|"), 20: ("functions", "graph of f with given max and min")},
        2: {1: ("gcse-algebra", "solve an equation with algebraic fractions"), 2: ("integration", "difference of two definite integrals"),
            3: ("proof", "claim about sqrt(xy) = sqrt(x)sqrt(y)"), 4: ("errors", "student's attempt: consecutive odd primes"),
            5: ("logic", "necessary/sufficient: k and an integral of sin 2x"), 6: ("exp-logs", "a^x = x: same number of solutions"),
            7: ("logic", "necessary but not sufficient: line with positive gradient and intercept"), 8: ("reasoning", "lines dividing a triangle into right-angled triangles"),
            9: ("logic", "pentagon statement, converse and contrapositive"), 10: ("errors", "solving x^4 - 2x^2 - 3 < 0 by completing the square"),
            11: ("logic", "if 2^k + 1 is prime then k is a power of 2"), 12: ("trig-functions", "number of solutions of sin x cos^2 x = p^2 sin x"),
            13: ("logic", "sufficient condition for three of four statements"), 14: ("straight-lines", "three lines ax + by + c = 0 ..."),
            15: ("number", "binary fractions"), 16: ("sequences-series", "recurrence with u1 = a, u2 = b"),
            17: ("integration", "integral of the ceiling function"), 18: ("quadratics", "x^4 + bx^2 + c = 0 has four real roots iff"),
            19: ("polynomials", "roots of f(x) and x f(x)"), 20: ("integration", "statements about I(p, q)")},
    },
    "2022": {
        1: {1: ("trig-functions", "2cos^4 - 5cos^2 + 3 = 0: number of solutions"), 2: ("circles", "when x^2 - 2px + y^2 - 6y ... is a circle"),
            3: ("integration", "f'(x) <= a with an integral condition"), 4: ("trig-triangles", "similar sectors: arc, area and perimeter"),
            5: ("sequences-series", "recurrence x(n+1) = x(n) + p x(n) + q"), 6: ("exp-logs", "integral between log2 5 and log2 20"),
            7: ("integration", "area enclosed by y = x^2 - 4|x| - 12"), 8: ("sequences-series", "geometric series: S30 - S20 = k S10"),
            9: ("trig-functions", "f - g = 2 sin x, fg = cos^2 x: minimum of f"), 10: ("functions", "translations of y = x^3"),
            11: ("exp-logs", "sum of logs from 1 to 100"), 12: ("quadratics", "family of quadratics y_k"),
            13: ("indices-surds", "surd expression with a and b"), 14: ("trig-triangles", "triangle in a circle of radius 6"),
            15: ("differentiation", "largest rectangle between two parabolas"), 16: ("trig-functions", "7x^4 - 6x^2 + 1 = 0 with cos to sin"),
            17: ("trig-triangles", "two non-congruent triangles: the ambiguous case with sides x - 1 and sqrt(-x^2 + 6x - 5)"), 18: ("graphs", "f(x) = x^2(x - 1)^2(x - 2) and g(x)"),
            19: ("circles", "two circles: C1 radius 5, C2 radius 4"), 20: ("graphs", "intersections of y = |x^2 - a^2| and y = a^2 |x - 1|")},
        2: {1: ("differentiation", "stationary points of 3x^4 + 4x^3 + 6x^2 - 5"), 2: ("binomial", "coefficient of x^5 in (1 + x)^5 times a sum"),
            3: ("proof", "counterexample: n prime, n^2 + 2 not prime"), 4: ("logic", "sufficient information to find a distance to a circle centre"),
            5: ("logic", "line through (1, 2): statement, converse, contrapositive"), 6: ("logic", "n odd vs median is in the list"),
            7: ("errors", "difference of consecutive cubes is always prime"), 8: ("reasoning", "pigeonhole in 1, 4, 7, ..., 70"),
            9: ("logic", "for all x, if x < k then x^2 < k"), 10: ("logic", "quantifier statements about real x and integer n"),
            11: ("geometry", "kite: necessary and sufficient for a right angle"), 12: ("integration", "ordering three integrals"),
            13: ("reasoning", "exists y with x - xy + y negative"), 14: ("simultaneous-inequalities", "two modulus inequalities"),
            15: ("exp-logs", "log_x y = z and log_y z = x"), 16: ("reasoning", "min and max of sequences a = b + c"),
            17: ("errors", "student proves the converse (cubic roots)"), 18: ("graphs", "identify graphs of (cos x)^cos x etc."),
            19: ("geometry", "polygon inscribed in a circle"), 20: ("functions", "compositions of cos and sin")},
    },
    "2021": {
        1: {1: ("circles", "two circles of equal radius"), 2: ("integration", "integral between turning points of a cubic"),
            3: ("sequences-series", "arithmetic and convergent geometric progressions"), 4: ("exp-logs", "minimum of 2^2x - 2^(x+3) + 4"),
            5: ("functions", "multiplicative function f(mn)"), 6: ("trig-functions", "max minus min of a trig function"),
            7: ("integration", "x f(x) > 0 and an integral"), 8: ("quadratics", "two tangent lines to a parabola"),
            9: ("graphs", "area enclosed by |x| + |y| = 1"), 10: ("integration", "trapezium rule for log10 x"),
            11: ("differentiation", "fraction of an interval where f decreases"), 12: ("quadratics", "minimum of x^4 - p^2 x^2 is -9"),
            13: ("integration", "integrals over unit intervals"), 14: ("trig-functions", "(x + 1)(3 - x) = 2(1 - cos x)"),
            15: ("functions", "g built from f(2^r x)"), 16: ("binomial", "third term of (a + bx)^n is 105x^2"),
            17: ("graphs", "sketch of sin(x^2 + y^2) = 1"), 18: ("graphs", "parabola rotated 90 degrees"),
            19: ("trig-functions", "equation with exactly three solutions"), 20: ("exp-logs", "length of a curve given by a log equation")},
        2: {1: ("integration", "definite integral of a rational expression"), 2: ("straight-lines", "diagonal of a square"),
            3: ("logic", "necessary conditions for a probability"), 4: ("proof", "counterexample: a divides bc"),
            5: ("errors", "first error: cos x = sqrt(1 - sin^2 x)"), 6: ("logic", "three roots vs two stationary points"),
            7: ("straight-lines", "line bisecting a circle and a square"), 8: ("differentiation", "exists c with p'(c) = 0"),
            9: ("graphs", "statements about a cubic"), 10: ("sequences-series", "sequence 15, 21, ..."),
            11: ("errors", "student's attempt: a^2 - 4b^3"), 12: ("integration", "statements about f <= g and integrals/derivatives"),
            13: ("simultaneous-inequalities", "region defined by two inequalities"), 14: ("exp-logs", "simultaneous equations with log2 y"),
            15: ("circles", "x^2 + ax + y^2 + by + c = 0"), 16: ("graphs", "x|x| = px + q: number of solutions"),
            17: ("exp-logs", "log2 log2 x and its square"), 18: ("trig-triangles", "can the triangle be drawn?"),
            19: ("trig-functions", "how many angles make an expression zero"), 20: ("functions", "f(n+1)(x) = |f(n)(x) + x|")},
    },
    "2020": {
        1: {1: ("differentiation", "derivative of (x^3 - 5x^2) / (2x sqrt x)"), 2: ("polynomials", "factors of 2x^3 + px^2 + q"),
            3: ("simultaneous-inequalities", "cubic and quadratic inequalities"), 4: ("sequences-series", "GP terms in an AP; sum to infinity 12"),
            5: ("quadratics", "curve y = px^2 + 6x - q"), 6: ("exp-logs", "maximum of an expression in 5^x"),
            7: ("indices-surds", "simultaneous equations in powers of 2"), 8: ("quadratics", "maximum of (p - x)(x + 2)"),
            9: ("quadratics", "roots alpha, beta of x^2 - 14x + 9"), 10: ("functions", "sequence of transformations of 4x^2"),
            11: ("quadratics", "quadratic through (2, 0) and (q, 0)"), 12: ("trig-functions", "3cos x = x: number of solutions"),
            13: ("binomial", "coefficient of x^2 y^4 in (1 + x + y^2)^7"), 14: ("integration", "area between y = mx and y = x^3 is 6"),
            15: ("exp-logs", "quartic in log2 x"), 16: ("circles", "common tangent to two circles"),
            17: ("graphs", "y = mx + c meets y = sqrt(x) twice"), 18: ("trig-functions", "1 - 2cos^2 x = |cos x|"),
            19: ("simultaneous-inequalities", "lowest integer with x^2 - 52x - 52 > 0"), 20: ("polynomials", "(x - a)(x^2 - x + a) = 0: exactly two roots")},
        2: {1: ("quadratics", "line crosses or touches a parabola"), 2: ("trig-functions", "tan = 2 in the fourth quadrant"),
            3: ("errors", "divisibility argument with 9^n and 3^n"), 4: ("proof", "N > 6 as a sum of two non-primes"),
            5: ("graphs", "graph of 2^x / (1 + 2^x)"), 6: ("logic", "necessary conditions for an integral to be zero"),
            7: ("geometry", "conditions on a parallelogram"), 8: ("errors", "proof about |a + b| < |a| + |b|"),
            9: ("trig-functions", "evaluating x sin x with a degrees calculator"), 10: ("reasoning", "inequalities in a, b, c, d"),
            11: ("reasoning", "spiral line on a grid"), 12: ("integration", "when the trapezium rule overestimates"),
            13: ("integration", "function identity involving integrals"), 14: ("sequences-series", "sum of first 4 terms = sum of first 8 terms"),
            15: ("trig-functions", "necessary and sufficient condition involving sin"), 16: ("errors", "student uses the FTC wrongly"),
            17: ("statistics", "means and medians of split sets"), 18: ("polynomials", "f - g > 0 for cubics"),
            19: ("reasoning", "nine people on a 3 by 3 grid"), 20: ("logic", "exactly one statement is true")},
    },
    "2019": {
        1: {1: ("quadratics", "quadratic through (1, -1) with vertex (-1, 3)"), 2: ("quadratics", "positive for all x: range of k"),
            3: ("binomial", "coefficient of x in a sum of (1 + x)^n"), 4: ("sequences-series", "sequence x(n+1) = sqrt(x(n))"),
            5: ("sequences-series", "S6 = 9 S3, seventh term 360"), 6: ("circles", "two circles touching"),
            7: ("differentiation", "gradient at x = -1 as a function of q"), 8: ("integration", "trapezium rule underestimate"),
            9: ("integration", "area between y = px and x = py"), 10: ("integration", "integral of |x|(1 - x)"),
            11: ("exp-logs", "simultaneous log equations"), 12: ("integration", "dV/dt = 24(t - 1)"),
            13: ("exp-logs", "maximum of 4^sin x - 4 . 2^sin x + 417"), 14: ("trig-functions", "simultaneous trig equations"),
            15: ("exp-logs", "2(9^x) + 8(3^x) = 4"), 16: ("integration", "combining integrals with unknown f"),
            17: ("trig-functions", "fraction of an interval satisfying a trig inequality"), 18: ("differentiation", "shortest distance from a parabola to a line"),
            19: ("trig-functions", "sum of sin(10 + 90k)"), 20: ("graphs", "range of k for curves to intersect")},
        2: {1: ("binomial", "coefficient of x^4 in (x^2/2 + x)^6"), 2: ("polynomials", "factors of 2x^3 + px^2 + q"),
            3: ("logic", "ab = ac: what must be true"), 4: ("proof", "conjecture about 10...01 being prime"),
            5: ("logic", "ab divisible by n: necessary/sufficient"), 6: ("errors", "student solves cos x + sin x tan x = 2 sin x - 1"),
            7: ("proof", "counterexample from 12^2 + 16^2 = 20^2"), 8: ("reasoning", "a < b < c < 0 inequalities"),
            9: ("reasoning", "40 chairs round a table"), 10: ("geometry", "necessary but not sufficient for a parallelogram"),
            11: ("sequences-series", "integer arithmetic series summing to 20"), 12: ("probability", "three probabilities for chosen students"),
            13: ("integration", "trapezium rule for sin^2 x overestimate"), 14: ("differentiation", "statements p(a), p(b), p'(a), p'(b)"),
            15: ("exp-logs", "log(ab^2 c) = 7 and similar"), 16: ("quadratics", "y = px^2 + qx + p: graph of p against roots"),
            17: ("logic", "multiple-choice options about a statement"), 18: ("simultaneous-inequalities", "a|x| + 1 >= |x - 2|"),
            19: ("indices-surds", "nested surds"), 20: ("functions", "reflect then translate the graph of f")},
    },
    "2018": {
        1: {1: ("integration", "integral of |3 - 2x|"), 2: ("sequences-series", "S5 = S8 in an arithmetic progression"),
            3: ("circles", "shortest distance between two circles"), 4: ("simultaneous-inequalities", "3x^2 + 2xy = 4, x + y = a"),
            5: ("polynomials", "cubic with coefficients 1, 2, 3 in some order"), 6: ("trig-functions", "x sin 2x = cos 2x: number of solutions"),
            7: ("binomial", "equal coefficients of x^6"), 8: ("sequences-series", "sum to infinity of squares and cubes"),
            9: ("differentiation", "2x^3 - 3x^2 - 12x + c: three real roots"), 10: ("simultaneous-inequalities", "|2 - x| <= 6, |y + 2| <= 4: max |xy|"),
            11: ("differentiation", "normal to y = 10 - x^2"), 12: ("graphs", "quartic x(x - p)(x - q)(r - x)"),
            13: ("differentiation", "graph of f': which point is a local minimum of f"), 14: ("exp-logs", "line through (3, log2 p) and (log2 p, 4)"),
            15: ("exp-logs", "3^x - sqrt(3)^(x+4) + 20 = 0"), 16: ("quadratics", "stationary point closest to the origin"),
            17: ("statistics", "exchanging data between two sets"), 18: ("trig-functions", "line of symmetry of sin(2x - 4pi/3)"),
            19: ("trig-triangles", "two possible triangles: the larger one"), 20: ("trig-functions", "sum of sin^2 0 to sin^2 90")},
        2: {1: ("differentiation", "f(x) = (x^3 - 4x)/... for x > 0"), 2: ("binomial", "constant term in (x - 2/x^2)^12"),
            3: ("errors", "average speed of a two-part journey"), 4: ("trig-functions", "cos x = c has two solutions: cos^2 2x = c^2"),
            5: ("geometry", "quadrilateral with perpendicular diagonals"), 6: ("proof", "counterexample: f' > 0 but f not positive"),
            7: ("sequences-series", "numbers in both arithmetic progressions"), 8: ("reasoning", "mountain profiles: counting"),
            9: ("errors", "attempt to solve 4x sqrt(2x - 1) = 10x - 5"), 10: ("functions", "symmetry conditions f(a - x) = f(a + x)"),
            11: ("graphs", "2^x = mx + c statements"), 12: ("proof", "N(Km + 1) - 1 is never prime"),
            13: ("errors", "attempted proof: tan > 0 implies sin + cos > 1"), 14: ("trig-triangles", "values of p that determine PQ uniquely"),
            15: ("differentiation", "x^3 + 3qx^2 + 2 with three distinct roots"), 16: ("sequences-series", "median of an integer arithmetic progression"),
            17: ("reasoning", "squaresum numbers"), 18: ("logic", "necessary condition for f(a) + f(b) >= f((a + b)/2)"),
            19: ("exp-logs", "inequalities in 2^x, 5^x, 7^x"), 20: ("graphs", "|x + p| + |x| = p has a solution")},
    },
    "2017": {
        1: {1: ("integration", "find y from dy/dx = 3x^2 - (2 - 3x)/x^3"), 2: ("differentiation", "f''(1) for (2/x - 1/(2x^2))^2"),
            3: ("straight-lines", "area enclosed by two perpendicular lines and the x-axis"), 4: ("polynomials", "remainder theorem with (px - 1)"),
            5: ("simultaneous-inequalities", "combine two inequalities into one"), 6: ("circles", "tangent to x^2 + y^2 = 144 through (20, 0)"),
            7: ("sequences-series", "p, q, p^2 arithmetic and p, p^2, q geometric"), 8: ("trig-functions", "(1 - 2 sin x) cos x >= 0"),
            9: ("circles", "regular hexagon inscribed in a circle"), 10: ("differentiation", "greatest gradient of a normal as p varies"),
            11: ("sequences-series", "recurrence x(n+1) = (23x(n) - 53)/(5x(n) + 1)"), 12: ("integration", "integral of f(x + 2) + 1"),
            13: ("binomial", "coefficient of x^4 is 8 times coefficient of x^2"), 14: ("exp-logs", "simultaneous equations in 2^x and 2^y"),
            15: ("integration", "trapezium rule over/under for three related curves"), 16: ("differentiation", "one function increasing, the other decreasing"),
            17: ("integration", "F(n) as an integral, G(n) as a sum"), 18: ("exp-logs", "translation of log10 x as a stretch"),
            19: ("simultaneous-inequalities", "solution set of x^2 + bcx + c^3 < 0"), 20: ("trig-triangles", "range of an angle in a triangle with sides a, a + d, a + 2d")},
        2: {1: ("differentiation", "derivative of (1 - 3x)^2 / (2x^(3/2))"), 2: ("straight-lines", "rectangle PQRS from two vertices"),
            3: ("sequences-series", "sum to infinity from the first and fourth terms"), 4: ("errors", "student finds sin 2x from tan x = 3"),
            5: ("proof", "91 = 7 x 13 as a counterexample"), 6: ("integration", "sequence defined by integrals"),
            7: ("graphs", "graphs of a^x and f(x)"), 8: ("exp-logs", "which number is smallest"),
            9: ("errors", "attempted proof of a^3 + b^3 = c^3 having no solutions"), 10: ("logic", "sufficient condition for an integral to be zero"),
            11: ("integration", "area under an increasing f between a and b"), 12: ("trig-functions", "graphs of sin 2x and cos 2x"),
            13: ("number", "standard form addition"), 14: ("quadratics", "graph of x^2 - 2Bx + c with B > b"),
            15: ("sequences-series", "Collatz-style recurrence"), 16: ("logic", "if f(x) integer for integer x then f'(x) ..."),
            17: ("reasoning", "'stapled' sets of whole numbers"), 18: ("errors", "solving (1/2)^n < 1/10 with logs"),
            19: ("logic", "sufficient condition for exactly one real root"), 20: ("reasoning", "forgotten password puzzle")},
    },
    "Practice": {
        1: {1: ("binomial", "expansion of (ax + b)^3"), 2: ("polynomials", "factorise a cubic with factor (x + 2)"),
            3: ("differentiation", "normal to y = 2/x^2: length PQ"), 4: ("sequences-series", "sum of (-1)^n terms"),
            5: ("integration", "area between y = x^2 - 1 and the x-axis"), 6: ("ratio-proportion", "mixing paints"),
            7: ("probability", "sports club: women who play tennis"), 8: ("trig-functions", "cos^2 2x + sqrt3 sin 2x - 7/4 = 0"),
            9: ("circles", "circle translated, reflected and enlarged"), 10: ("graphs", "x tan x = 1: number of solutions"),
            11: ("exp-logs", "4^2x + 12 = 2^(2x+3)"), 12: ("differentiation", "largest cylinder inside a sphere"),
            13: ("graphs", "real roots of 3x^5 - 10x^3 - 120x + 30"), 14: ("sequences-series", "sum of two geometric series"),
            15: ("differentiation", "least gradient at x = 1 as a varies"), 16: ("exp-logs", "simultaneous log10 equations"),
            17: ("trig-functions", "where (1 + 2cos x)cos 2x is negative"), 18: ("differentiation", "where (1 - x)/x^(2/3) decreases"),
            19: ("binomial", "coefficients in (1 + 2x + 3x^2)^6 and (1 - ax^2)^5"), 20: ("mensuration", "shortest path on a pyramid")},
        2: {1: ("integration", "integral of (x^2 - 4/x^2)^2"), 2: ("differentiation", "derivative of (x^2 + 5)(2x)/x^(3/4)"),
            3: ("trig-functions", "8 sin^2 x + 4 cos^2 x = 7"), 4: ("reasoning", "five urns, exactly one true statement"),
            5: ("proof", "counting counterexamples to a primality claim"), 6: ("differentiation", "sequence f(n+1) = x f(n)'"),
            7: ("proof", "ordering the lines of a logarithm proof"), 8: ("simultaneous-inequalities", "region x + y > 6, x - y > -4"),
            9: ("geometry", "conditions implying congruent triangles"), 10: ("logic", "sufficient to conclude x < y"),
            11: ("graphs", "polynomial with roots at -p and p"), 12: ("sequences-series", "S8 > 3S6: signs of a and d"),
            13: ("errors", "attempted proof about a dividing bc"), 14: ("graphs", "quartic: numbers of solutions of f(x) = k"),
            15: ("quadratics", "roots differ by between 2 and 4: iff condition"), 16: ("geometry", "line through the diagonals' intersection of a trapezium"),
            17: ("trig-functions", "y = 3 sin x + 2 and y = x + c"), 18: ("integration", "counterexample about integrals of f^2 and f"),
            19: ("mensuration", "plans and elevations: counting cubes"), 20: ("geometry", "interior angles of regular polygons in ratio 3 : 4")},
    },
    "Specimen": {
        1: {1: ("simultaneous-inequalities", "simultaneous equations: sum of solutions"), 2: ("trig-functions", "sin 3x = cos 3x on [0, 4pi]"),
            3: ("straight-lines", "perpendicular bisector meets an axis"), 4: ("simultaneous-inequalities", "set of values satisfying an inequality"),
            5: ("exp-logs", "log equation: express in terms of ..."), 6: ("polynomials", "(x - 2) is a factor: sum of possible values"),
            7: ("probability", "two balls without replacement"), 8: ("exp-logs", "positive reals and a log relationship"),
            9: ("quadratics", "roots differ by 2"), 10: ("functions", "cos x reflected then translated"),
            11: ("polynomials", "sum of roots of a factorised quartic"), 12: ("mensuration", "triangular prism: surface area and volume"),
            13: ("graphs", "number of real roots of a quartic"), 14: ("ratio-proportion", "related positive variables"),
            15: ("differentiation", "smallest possible value as x varies"), 16: ("number", "when an expression is an integer"),
            17: ("quadratics", "real distinct roots for all non-zero k"), 18: ("trig-functions", "total length of intervals: tan and sin conditions"),
            19: ("sequences-series", "geometric series terms forming an arithmetic series"), 20: ("binomial", "coefficient in an expansion")},
        2: {1: ("circles", "radius of x^2 + y^2 - 8x + 12y + 15 = 0"), 2: ("differentiation", "gradient at x = 2"),
            3: ("errors", "attempt to solve sqrt(x + 5) = x + 3"), 4: ("logic", "cards with letters and numbers: counterexample"),
            5: ("exp-logs", "approximating log 2 from 2^10 ~ 10^3"), 6: ("number", "bounds: area and width of a rectangle"),
            7: ("graphs", "sketch of (x + y)(x - y + 1) = ..."), 8: ("proof", "sum of four consecutive integers is a multiple of 6"),
            9: ("logic", "negating 'every day next week'"), 10: ("graphs", "sketch of log x for x > 1"),
            11: ("trig-functions", "which value is largest (radians)"), 12: ("polynomials", "deductions from p(1) = 2"),
            13: ("reasoning", "five runners: who beat whom"), 14: ("graphs", "sketch of a degree-5 polynomial"),
            15: ("reasoning", "three statements about real numbers"), 16: ("sequences-series", "sequence with (-1)^n terms"),
            17: ("reasoning", "S-numbers"), 18: ("statistics", "five numbers with mean 0 and range 20"),
            19: ("graphs", "equation with three real roots, one positive"), 20: ("reasoning", "five logicians")},
    },
}
