"""Full teaching solutions: mixed Paper 2-style questions (X2-xx)."""
from gen.model import Sol

SOLUTIONS = {

"X2-01": Sol(
    idea=r"Three claims about a quadratic. Each is settled by the discriminant, by a well-chosen substitution, or by the root-product relationship.",
    steps=[
        (r"I: $p^2 < 4q$ means the discriminant $p^2 - 4q < 0$, so $x^2+px+q$ has no real roots; with a positive $x^2$ coefficient the graph lies entirely above the axis. **True.**",
         r"No roots plus an upward parabola means always positive - the graph never reaches the axis."),
        (r"II: if $x^2+px+q > 0$ for **all** $x$, then in particular at $x = 0$: $q > 0$. **True.**",
         r"Substituting a convenient value is the quickest way to extract information from a universal statement."),
        (r"III: the product of the roots is $q$. If $q<0$ then $p^2 - 4q > p^2 \geq 0$, so the roots are real and distinct, and their product being negative makes them opposite in sign. **True.**",
         r"For $x^2+px+q$ the sum of roots is $-p$ and the product is $q$."),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Reading I's condition as $p^2 > 4q$ - that would give two real roots and the opposite conclusion.",
              r"Forgetting to check in III that the roots are **real**; a negative product alone would be meaningless for complex roots.",
              r"Trying to prove II with a general argument when $x=0$ settles it in one line."],
    takeaway=r"Discriminant controls the number of roots; $x=0$ extracts the constant term; sum and product of roots are $-b/a$ and $c/a$."),

"X2-02": Sol(
    idea=r"A necessary/sufficient question about polynomials. Test each direction, and look for a boundary case to break the converse.",
    steps=[
        (r"Sufficiency: if $f'(x)>0$ for all $x$, then $f$ is strictly increasing, so it takes each value at most once - at most one root.",
         r"A strictly increasing function cannot return to a value it has already passed."),
        (r"Moreover such an $f$ must have odd degree (an even-degree polynomial turns), so it goes from $-\infty$ to $+\infty$ and crosses the axis. Exactly one root: $P \Rightarrow Q$. **Sufficient.**",
         r"Both halves are needed: 'at most one' plus 'at least one'."),
        (r"Necessity: find an $f$ with exactly one root but $f'$ not always positive. Take $f(x) = x^3$: one root at $0$, but $f'(0) = 0$.",
         r"A stationary point of inflexion satisfies $Q$ without satisfying $P$."),
        (r"So $P$ is sufficient but not necessary.",
         r"Match to the list."),
    ],
    pitfalls=[r"Claiming $P$ is necessary because 'one root suggests increasing' - $x^3$ and also $x^2$-type shifts break that.",
              r"Forgetting that $f'>0$ forces odd degree, so 'at least one root' still needs justifying."],
    takeaway=r"Strictly increasing $\Rightarrow$ at most one root; but a single root does not force a strictly positive derivative ($x^3$)."),

"X2-03": Sol(
    idea=r"A hard 'must be true' about integrals. Two claims import assumptions the question never makes.",
    steps=[
        (r"III: $\int_0^4 = \int_0^2 + \int_2^4$, and the left side is $0$, so $\int_0^2 = -\int_2^4$. **True** - pure algebra of integrals.",
         r"Splitting an integral at an interior point is always valid where the integral exists."),
        (r"I: 'zero integral $\Rightarrow$ $f$ hits zero' is the intermediate value theorem in disguise - but that needs **continuity**, which is not given.",
         r"Read the hypotheses: it only says $f$ is defined for all real $x$."),
        (r"Counterexample for I: a step function equal to $-1$ on $[0,2)$ and $1$ on $[2,4]$ has integral $0$ but never equals $0$. **False.**",
         r"It jumps straight past zero."),
        (r"II: 'integral $0$' means signed areas cancel, not that the area is $0$. Take $f(x) = x-2$: $\int_0^4 (x-2)dx = 0$, but the area is $2 + 2 = 4$. **False.**",
         r"Area counts the region below the axis as positive; the integral counts it as negative."),
        (r"So III only.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting I by silently assuming $f$ is continuous - an assumption the question deliberately withholds.",
              r"Treating 'integral' and 'area' as the same thing; they agree only when $f \geq 0$ throughout."],
    takeaway=r"Integral $\neq$ area when the function changes sign; and the intermediate value theorem requires continuity, which must be **given**."),

"X2-04": Sol(
    idea=r"A definition-driven case: the convergence condition for a geometric series is exactly the stated inequality, so both directions hold.",
    steps=[
        (r"A geometric series with $a \neq 0$ has a sum to infinity if and only if $|r| < 1$.",
         r"The partial sums $\frac{a(1-r^n)}{1-r}$ converge precisely when $r^n \to 0$."),
        (r"$|r| < 1$ is the same statement as $-1 < r < 1$.",
         r"Modulus inequalities unfold into a double inequality."),
        (r"So $P$ and $Q$ are equivalent: necessary **and** sufficient.",
         r"An 'if and only if' condition gives both directions at once."),
    ],
    pitfalls=[r"Forgetting the case $r = \pm1$: $r=1$ gives partial sums $na$, which diverge; $r=-1$ oscillates. Both are correctly excluded.",
              r"Answering 'sufficient but not necessary' from habit - here no counterexample exists.",
              r"Overlooking why $a \neq 0$ is stated: with $a = 0$ every $r$ would give a (trivial) sum."],
    takeaway=r"Geometric series converge $\iff |r|<1$, and then $S_\infty = \frac{a}{1-r}$. An 'if and only if' condition is necessary and sufficient."),

"X2-05": Sol(
    idea=r"Three claims about two distinct straight lines. Each follows from what gradients and intercepts mean.",
    steps=[
        (r"I: $m_1m_2 = -1$ means the lines are perpendicular, so $m_1 \neq m_2$ and the lines are not parallel - they meet exactly once. **True.**",
         r"Two non-parallel straight lines always meet at exactly one point."),
        (r"II: $m_1 = m_2$ with the lines **distinct** means $c_1 \neq c_2$: parallel and separate, so they never meet. **True.**",
         r"The word 'distinct' in the question is doing real work - without it the lines could coincide."),
        (r"III: on the $y$-axis $x = 0$, so the two $y$-values are $c_1$ and $c_2$. Meeting there forces $c_1 = c_2$. **True.**",
         r"Substituting $x = 0$ into both equations."),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Rejecting II by imagining the lines could coincide - 'distinct' rules that out.",
              r"Rejecting III by thinking they might meet elsewhere; the claim conditions on them meeting **on the $y$-axis**."],
    takeaway=r"Same gradient and distinct $\Rightarrow$ parallel, never meet. Different gradients $\Rightarrow$ exactly one intersection. Read 'distinct' carefully."),

"X2-06": Sol(
    idea=r"To break an inequality claim, look for the case where the two sides are closest - here small values, where logs go to zero or negative.",
    steps=[
        (r"Test $x = y = 1$: left side $\log_{10}2 \approx 0.30$; right side $\log_{10}1 + \log_{10}1 = 0$.",
         r"$\log 1 = 0$ for any base, so the right side collapses."),
        (r"$0.30 > 0$, so the claimed inequality $\leq$ fails. **Counterexample.**",
         r"Hypothesis satisfied ($x,y$ positive), conclusion false."),
        (r"Why the others work: $\log x + \log y = \log(xy)$, and $\log$ is increasing, so the claim is just $x+y \leq xy$. For $x=y=2$: $4 \leq 4$ ✓; $x=y=4$: $8 \leq 16$ ✓; $x=y=5$: $10\leq25$ ✓; $x=10,y=100$: $110 \leq 1000$ ✓.",
         r"Converting the log inequality into an algebraic one makes all five cases quick to check."),
    ],
    pitfalls=[r"Trying large values, where $xy$ dwarfs $x+y$ and the claim comfortably holds.",
              r"Forgetting $\log_{10}1 = 0$ and miscomputing the right side.",
              r"Thinking $\log(x+y) = \log x + \log y$ - that is the error the whole question is built on."],
    takeaway=r"$\log x + \log y = \log(xy)$, never $\log(x+y)$. Test inequality claims near the boundary, where the sides are closest."),

"X2-07": Sol(
    idea=r"Read the claims off the graph of $y = \sin x$ over one period, then remember the range.",
    steps=[
        (r"I: for $-1<k<1$ the horizontal line $y=k$ cuts one period of the sine curve exactly twice. **True.**",
         r"Sine rises from $0$ to $1$, falls to $-1$ and returns - a strictly-between value is hit once on the way down and once elsewhere in $[0, 2\pi)$."),
        (r"II: $k=1$ is reached only at the single peak $x = \frac{\pi}{2}$. **True.**",
         r"The maximum is attained once per period."),
        (r"III: for $|k| > 1$ there is no solution at all - $\sin x = 2$ is impossible. **False.**",
         r"The range of sine is $[-1,1]$."),
        (r"So I and II.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting III by forgetting the range restriction.",
              r"Rejecting II by counting $x = \frac{\pi}{2}$ and $x = \frac{5\pi}{2}$ - the second is outside $0 \leq x < 2\pi$.",
              r"Rejecting I because $k=0$ feels special: $\sin x = 0$ gives $x = 0$ and $x=\pi$ in the interval - still exactly two."],
    takeaway=r"Per period, $\sin x = k$ has two solutions for $|k|<1$, one for $|k|=1$ and none for $|k|>1$. Sketch the line across the curve."),

"X2-08": Sol(
    idea=r"The factor theorem gives one direction; a repeated factor is strictly more than a root.",
    steps=[
        (r"If $(x-2)^2$ is a factor, then $(x-2)$ is a factor, so $p(2) = 0$: $Q \Rightarrow P$. **$P$ is necessary.**",
         r"Factor theorem: $(x-a)$ is a factor exactly when $p(a)=0$."),
        (r"Is $P$ sufficient? Take $p(x) = x-2$: $p(2)=0$, but $(x-2)^2$ does not divide a degree-$1$ polynomial.",
         r"A single root is not a repeated root."),
        (r"So $P$ is necessary but not sufficient.",
         r"Note the direction: the weaker condition is necessary for the stronger one."),
    ],
    pitfalls=[r"Answering 'sufficient but not necessary' - the common pattern, but reversed here.",
              r"Thinking $p(2)=0$ and $p'(2)=0$ together would be needed; that is exactly the extra condition for a repeated root, and its absence is the point."],
    takeaway=r"$p(a)=0 \iff (x-a)$ is a factor; a **repeated** factor also needs $p'(a)=0$."),

"X2-09": Sol(
    idea=r"Intersections and roots. Distinguish a root from a **crossing**, and resist assuming the functions are polynomials.",
    steps=[
        (r"I: the graphs meet where $f(x)=g(x)$, so three intersection points means exactly three solutions. **True** - it is the definition.",
         r"Each intersection point has a distinct $x$-value, since a graph has one $y$ per $x$."),
        (r"II: at a root of $f-g$ the graph could **touch** the $x$-axis and turn back rather than cross - a repeated root.",
         r"Meeting and crossing are different: $y = x^2$ meets the axis but does not cross it."),
        (r"So the number of crossings could be fewer than three. **False.**",
         r"For instance $f-g = x^2(x-1)$ meets the axis at $0$ and $1$ but crosses only at $1$."),
        (r"III: nothing says $f$ and $g$ are polynomials. Take $f(x)=\sin x$ and a suitable straight line $g$, meeting three times. **False.**",
         r"Read the hypotheses: only 'the graphs of $y=f(x)$ and $y=g(x)$' is given."),
        (r"So I only.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting II by treating 'crosses' as a synonym for 'meets'.",
              r"Accepting III by assuming a degree just because three intersections are mentioned."],
    takeaway=r"Intersections $=$ solutions of $f=g$; but crossing the axis needs a sign change, and never assume a function type that was not stated."),

"X2-10": Sol(
    idea=r"Translate the geometry into a distance comparison: circle versus line depends on centre-to-line distance against the radius.",
    steps=[
        (r"The perpendicular distance from the centre $(a,b)$ to the $x$-axis is $|b|$.",
         r"The $x$-axis is $y = 0$, so the vertical distance is the size of the $y$-coordinate."),
        (r"If $|b| < r$ the circle reaches across the axis and cuts it twice; if $|b| = r$ it touches once; if $|b| > r$ it misses entirely.",
         r"Three cases, decided by comparing distance with radius."),
        (r"So 'two distinct points' happens exactly when $r > |b|$ - the two statements are equivalent.",
         r"Necessary **and** sufficient."),
    ],
    pitfalls=[r"Writing the condition as $r > b$, which fails for a centre below the axis ($b$ negative). The modulus matters.",
              r"Including the tangent case $r = |b|$, which gives one point, not two."],
    takeaway=r"Circle versus line: compare the perpendicular distance from the centre with $r$ - less gives two points, equal one, greater none."),

"X2-11": Sol(
    idea=r"Composite transformations, applied in the stated order. Each transformation acts on the function you currently have.",
    steps=[
        (r"Translate $y=x^2$ by $2$ in the positive $x$-direction: replace $x$ by $x-2$, giving $y = (x-2)^2$.",
         r"A shift **right** subtracts inside the bracket - counter-intuitive but standard."),
        (r"Now reflect in the $y$-axis: replace $x$ by $-x$, giving $y = (-x-2)^2$.",
         r"Reflection in the $y$-axis is the substitution $x \to -x$."),
        (r"Simplify: $(-x-2)^2 = \left(-(x+2)\right)^2 = (x+2)^2$. So $g(x) = (x+2)^2$ - **I is true, II is false.**",
         r"Squaring removes the overall minus sign."),
        (r"III: $(x+2)^2$ has its vertex where $x+2=0$, i.e. at $(-2,0)$. **True.**",
         r"Consistent: the vertex moved right to $(2,0)$, then reflected to $(-2,0)$."),
        (r"So I and III.",
         r"Match to the list."),
    ],
    pitfalls=[r"Doing the transformations in the wrong order - reflecting first then translating gives $(x-2)^2$ instead.",
              r"Shifting right by adding $2$ inside the bracket.",
              r"Forgetting to simplify $(-x-2)^2$, and so failing to recognise it as $(x+2)^2$."],
    takeaway=r"Right by $a$: $x \to x-a$. Reflect in the $y$-axis: $x \to -x$. Apply them in the order given, tracking the vertex as a check."),

"X2-12": Sol(
    idea=r"Three cancellation claims, all made safe by the stated positivity. Check what each would need.",
    steps=[
        (r"I: $a^2=b^2$ gives $a = \pm b$ in general - but $a,b>0$ rules out $a=-b$, so $a=b$. **True.**",
         r"The positivity hypothesis is exactly what repairs the usual counterexample."),
        (r"II: $2^x$ is a strictly increasing function, so it takes each value once: $2^a=2^b \Rightarrow a=b$. **True.**",
         r"One-to-one functions can be cancelled; equivalently take $\log_2$ of both sides."),
        (r"III: $a^b = 1$ with $a,b>0$. Take logs: $b\log a = 0$. Since $b>0$, $\log a = 0$, so $a=1$. **True.**",
         r"Taking logs turns the exponent into a factor, and a product is zero only if a factor is."),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Rejecting I by recalling the counterexample $2$ and $-2$ - forbidden here, since both are positive.",
              r"Rejecting III by thinking of $a^0=1$ - that needs $b=0$, which positivity forbids. (And $(-1)^2 = 1$ needs a negative $a$.)",
              r"Overlooking how much work the phrase 'positive real numbers' is doing in all three."],
    takeaway=r"Read the domain restrictions first - positivity makes squaring and exponentiation reversible, when in general they are not."),

"X2-13": Sol(
    idea=r"Three binomial facts: the general term, substituting a value, and a term-by-term inequality.",
    steps=[
        (r"I: the coefficient of $x^r$ in $(1+x)^m$ is $\binom mr$. With $m = 2n$ and $r = n$ that is $\binom{2n}{n}$. **True.**",
         r"Straight from the binomial theorem."),
        (r"II: the sum of the coefficients of any polynomial is its value at $x=1$. Here $(1-1)^n = 0^n = 0$ for $n \geq 1$. **True.**",
         r"Substituting $x=1$ makes every power equal $1$, so the value is the coefficient sum."),
        (r"III: for $x \geq 0$, $(1+x)^n = 1 + nx + \binom n2 x^2 + \cdots$, and every omitted term is non-negative. So $(1+x)^n \geq 1+nx$. **True.**",
         r"All binomial coefficients and all powers of a non-negative $x$ are non-negative."),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Thinking II fails for $n=0$ - the question says $n$ is a positive integer.",
              r"Doubting III for large $n$; the extra terms only help, since $x \geq 0$.",
              r"Confusing $\binom{2n}{n}$ with $\binom{2n}{2}$ or $2\binom nn$."],
    takeaway=r"Sum of coefficients $=$ value at $x=1$; and $(1+x)^n \geq 1+nx$ for $x \geq 0$ (Bernoulli) follows from discarding non-negative terms."),

"X2-14": Sol(
    idea=r"Solve the quadratic inequality properly, then compare the two solution sets as intervals.",
    steps=[
        (r"$x^2<4$ means $|x|<2$, i.e. $-2<x<2$.",
         r"A quadratic inequality of this shape gives an interval **between** the roots."),
        (r"Every $x$ in $(-2,2)$ satisfies $x<2$, so $P \Rightarrow Q$: **sufficient.**",
         r"$(-2,2)$ is contained in $(-\infty,2)$."),
        (r"Is it necessary? Take $x=-5$: $x<2$ holds but $x^2 = 25 \not<4$. So $Q \not\Rightarrow P$: **not necessary.**",
         r"The larger set contains points outside the smaller one."),
        (r"So $P$ is sufficient but not necessary.",
         r"Whenever one solution set sits strictly inside another, the inner condition is sufficient but not necessary."),
    ],
    pitfalls=[r"Solving $x^2<4$ as $x<2$ and concluding the conditions are equivalent - that drops the lower bound.",
              r"Solving it as $x<-2$ or $x>2$, which is the solution of $x^2>4$."],
    takeaway=r"Compare conditions as **sets**: a subset is sufficient for the superset, the superset necessary for the subset."),

"X2-15": Sol(
    idea=r"Pythagoras **and** its converse both hold, so this is a genuine equivalence - best seen through the cosine rule.",
    steps=[
        (r"The cosine rule gives $a^2 = b^2+c^2-2bc\cos A$, so $\cos A = \dfrac{b^2+c^2-a^2}{2bc}$.",
         r"Rearranging the cosine rule turns both statements into one equation."),
        (r"$a^2 = b^2+c^2$ makes the numerator zero, so $\cos A = 0$ and (in a triangle) $A = 90^\circ$.",
         r"$2bc \neq 0$ since side lengths are positive; and $0^\circ<A<180^\circ$ makes $A=90^\circ$ the only solution of $\cos A = 0$."),
        (r"Conversely $A = 90^\circ$ gives $\cos A = 0$, so $b^2+c^2-a^2 = 0$.",
         r"The same equation, read the other way."),
        (r"So $P$ and $Q$ are equivalent: necessary and sufficient.",
         r"This is Pythagoras together with its converse."),
    ],
    pitfalls=[r"Assuming only the forward direction (right angle $\Rightarrow$ Pythagoras) and answering 'necessary but not sufficient'.",
              r"Forgetting that $a$ must be the side **opposite** $A$ for the relation to hold."],
    takeaway=r"The cosine rule contains Pythagoras and its converse: $\cos A = 0 \iff a^2 = b^2+c^2$, with $a$ opposite $A$."),

"X2-16": Sol(
    idea=r"Classify stationary points by whether $f'$ **changes sign** - a squared factor does not change sign.",
    steps=[
        (r"$f'(x) = (x-1)(x-3)^2$, so $f'=0$ at $x=1$ and $x=3$.",
         r"Stationary points are the roots of $f'$."),
        (r"Sign of $f'$: $(x-3)^2 \geq 0$ always, so the sign is that of $(x-1)$. Negative for $x<1$, positive for $x>1$ (zero at $x=3$).",
         r"An even-power factor contributes no sign change."),
        (r"I: $f'$ goes negative $\to$ positive at $x=1$, so a local **minimum**. **True.**",
         r"Falling then rising."),
        (r"II: at $x=3$, $f'$ is positive on both sides, so no turning point - a stationary point of inflexion. **False.**",
         r"The squared factor is precisely why there is no maximum here."),
        (r"III: for $x>1$, $f' \geq 0$ with equality only at the isolated point $x=3$, so $f$ is increasing. **True.**",
         r"An isolated zero of the derivative does not interrupt increase."),
        (r"So I and III.",
         r"Match to the list."),
    ],
    pitfalls=[r"Assuming every root of $f'$ is a turning point and alternating min/max - the repeated root breaks the alternation.",
              r"Rejecting III because $f'(3)=0$; increase needs $f' \geq 0$ with no interval of equality."],
    takeaway=r"Odd-power factors of $f'$ change sign (turning point); even-power factors do not (stationary inflexion)."),

"X2-17": Sol(
    idea=r"Whether the trapezium rule over- or under-estimates depends on the **concavity** of the curve.",
    steps=[
        (r"The trapezium rule replaces the curve on each strip by the straight chord joining the endpoints.",
         r"Its estimate is the area under those chords."),
        (r"$y=\sqrt x$ is concave: it rises steeply then flattens, bending downwards.",
         r"Its second derivative $-\frac14x^{-3/2}$ is negative for $x>0$ - or just picture the shape."),
        (r"For a concave curve every chord lies **below** the arc, so each trapezium sits below the true region.",
         r"That is what concavity means geometrically."),
        (r"So the estimate is an underestimate, for every $n$.",
         r"The number of strips affects accuracy, not direction."),
    ],
    pitfalls=[r"Assuming the trapezium rule always overestimates - true only for convex (upward-bending) curves such as $y=x^2$.",
              r"Thinking the parity of $n$ matters - that is Simpson's rule, which needs an even number of strips.",
              r"Answering 'cannot be decided' when the shape settles it."],
    takeaway=r"Trapezium rule: convex curve $\Rightarrow$ overestimate, concave curve $\Rightarrow$ underestimate. Sketch and look at the bend."),

"X2-18": Sol(
    idea=r"Three number-theory statements about primality testing, two of which are contrapositives of each other.",
    steps=[
        (r"I: if $n$ is composite write $n = ab$ with $1<a\leq b$. Then $a^2 \leq ab = n$, so $a \leq \sqrt n$.",
         r"The smaller factor of a pair cannot exceed the square root, or the product would be too big."),
        (r"$a>1$ has a prime factor, which is at most $a \leq \sqrt n$. So $n$ has a prime factor $\leq \sqrt n$. **True.**",
         r"Every integer greater than $1$ has a prime factor, and it cannot exceed the number itself."),
        (r"II: 'no prime factor $\leq\sqrt n$ $\Rightarrow$ $n$ prime' is exactly the contrapositive of I, so it is **True** automatically.",
         r"Contrapositives share truth values - no separate work needed."),
        (r"III: 'if $n$ is prime it has no factor strictly between $1$ and $n$' is the definition of prime. **True.**",
         r"A prime's only positive factors are $1$ and itself."),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Treating II as the converse of I and rejecting it; it is the contrapositive (negate and swap).",
              r"Wording III as 'no factors at all', which is wrong: $1$ and $n$ are factors."],
    takeaway=r"To test $n$ for primality, trial-divide by primes up to $\sqrt n$ - and I/II are the two readings of why that works."),

"X2-19": Sol(
    idea=r"Relating mutual exclusivity to independence. One implication holds; the converse has easy counterexamples.",
    steps=[
        (r"If $A,B$ are mutually exclusive, $P(A\cap B)=0$. But $P(A)P(B)>0$ since both probabilities are positive.",
         r"The positivity hypothesis is what makes the argument work."),
        (r"So $P(A\cap B) \neq P(A)P(B)$: they are **not** independent. $P \Rightarrow Q$: **sufficient.**",
         r"Independence is exactly the equality that fails here."),
        (r"Necessity: find dependent events that are **not** mutually exclusive. Roll a die with $A$: 'even' and $B$: 'at most $3$'. Then $P(A\cap B) = P(\{2\}) = \frac16$, but $P(A)P(B) = \frac12 \times \frac12 = \frac14$.",
         r"Unequal, so they are dependent - yet they overlap, so they are not mutually exclusive."),
        (r"So $P$ is sufficient but not necessary.",
         r"Match to the list."),
    ],
    pitfalls=[r"Treating mutually exclusive and independent as opposites in a way that makes them necessary for each other - dependence has many other causes.",
              r"Forgetting the hypothesis $P(A),P(B)>0$; with a zero probability, events can be both mutually exclusive and independent."],
    takeaway=r"For events of positive probability, mutually exclusive $\Rightarrow$ dependent, but not conversely."),

"X2-20": Sol(
    idea=r"A quadrilateral hierarchy question. Bisecting diagonals characterise parallelograms, a larger class than rectangles.",
    steps=[
        (r"Every rectangle is a parallelogram, and a parallelogram's diagonals bisect each other. So $Q \Rightarrow P$: **$P$ is necessary.**",
         r"Opposite sides equal and parallel forces the diagonals to share a midpoint."),
        (r"Is $P$ sufficient? Take a non-rectangular parallelogram, e.g. a rhombus with angles $60^\circ/120^\circ$: diagonals bisect each other, but it is not a rectangle.",
         r"Bisecting diagonals say nothing about the angles."),
        (r"So $P$ is necessary but not sufficient.",
         r"For a rectangle you also need the diagonals to be **equal** in length."),
    ],
    pitfalls=[r"Answering 'necessary and sufficient' by confusing 'bisect each other' with 'bisect each other and are equal'.",
              r"Getting the direction backwards: the broader property (parallelogram) is necessary for the narrower one (rectangle)."],
    takeaway=r"Diagonals bisect each other $\iff$ parallelogram; add equal diagonals for a rectangle, add perpendicular for a rhombus."),

"X2-21": Sol(
    idea=r"Three claims about a quartic. Two follow from degree; the first needs a counterexample.",
    steps=[
        (r"I: must a degree-$4$ polynomial have a real root? No: $x^4+1 \geq 1 > 0$ for all real $x$. **False.**",
         r"Even-degree polynomials can stay entirely above the axis - unlike odd-degree ones."),
        (r"II: a polynomial of degree $n$ has at most $n$ real roots, so at most $4$. **True.**",
         r"Each root supplies a linear factor; more than $4$ would exceed the degree."),
        (r"III: as $x \to \pm\infty$, a quartic tends to the same infinity at both ends (the sign of the leading coefficient).",
         r"Even powers dominate and are positive at both extremes."),
        (r"A continuous function going to the same infinity both ways must turn round somewhere, so it has at least one turning point. **True.**",
         r"It has a global minimum (or maximum) at a finite point."),
        (r"So II and III.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting I by analogy with odd-degree polynomials, which **must** have a real root.",
              r"Reading II as 'exactly four roots' - repeated roots and non-real roots reduce the count."],
    takeaway=r"Odd degree guarantees a real root; even degree guarantees a turning point. Degree $n$ caps the real roots at $n$."),

"X2-22": Sol(
    idea=r"Exponential versus quadratic growth: the exponential eventually wins, but there is a window where it loses. Test values inside that window.",
    steps=[
        (r"Check the candidates: $x=0$ gives $1>0$ ✓; $x=1$ gives $2>1$ ✓; $x=5$ gives $32>25$ ✓; $x=10$ gives $1024>100$ ✓.",
         r"Evaluate both sides for each - no cleverness needed."),
        (r"$x=3$: $2^3 = 8$ and $3^2 = 9$. Since $8 < 9$, the claim fails. **Counterexample.**",
         r"Hypothesis ($x$ real) satisfied, conclusion false."),
        (r"Why here? $2^x$ and $x^2$ cross at $x=2$ (both $4$) and again near $x=4$ (both $16$), so the quadratic is ahead between them.",
         r"Knowing where the curves cross tells you exactly where to hunt."),
    ],
    pitfalls=[r"Testing only large $x$, where the exponential dominates and the claim holds.",
              r"Overlooking the window: the two sides are equal at $x=2$ and $x=4$, so the quadratic leads strictly between them - that is where a counterexample must lie.",
              r"Assuming exponentials always beat polynomials - true only eventually."],
    takeaway=r"$2^x$ and $x^2$ meet at $x=2$ and $x=4$; between them the quadratic is larger. 'Eventually bigger' is not 'always bigger'."),

"X2-23": Sol(
    idea=r"Three claims about an arithmetic sequence, settled by the $n$th-term and sum formulas.",
    steps=[
        (r"I: the terms are $a+(n-1)d$ with $d>0$, which increases without bound, so beyond some point every term is positive. **True.**",
         r"A positive common difference eventually overcomes any negative start."),
        (r"II: $S_n = \frac n2\left(2a+(n-1)d\right) = \frac d2 n^2 + \left(a - \frac d2\right)n$ - a quadratic in $n$ (with $d \neq 0$, so the $n^2$ term survives). **True.**",
         r"Expand and collect powers of $n$; the hypothesis $d \neq 0$ is what makes it genuinely quadratic."),
        (r"III: $S_n$ is a sum of $n$ integers $a, a+d, \ldots$, hence an integer. **True.**",
         r"Sums of integers are integers - no need to worry about the $\frac n2$ in the formula, since the bracket is even when $n$ is odd and vice versa."),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Rejecting III because the formula contains $\frac n2$ - the product still comes out whole.",
              r"Rejecting II if $d$ were $0$ (linear) - but the question states $d \neq 0$.",
              r"Reading I as 'every term is positive' rather than 'every term after some point'."],
    takeaway=r"$S_n$ for an arithmetic series is quadratic in $n$; check the stated conditions ($a, d$ non-zero) before dismissing a claim."),

"X2-24": Sol(
    idea=r"Cubing preserves sign in both directions, so this is an equivalence - unlike squaring.",
    steps=[
        (r"If $x>0$ then $x^3 = x \cdot x \cdot x > 0$: **sufficient.**",
         r"A product of three positives is positive."),
        (r"Conversely, if $x \leq 0$ then $x^3 \leq 0$ (negative cubed is negative, and $0^3=0$). So $x^3>0$ forces $x>0$: **necessary.**",
         r"Proved by contrapositive - check the negative and zero cases rather than hunting for a counterexample."),
        (r"So $P$ is necessary and sufficient.",
         r"Cubing is a strictly increasing, sign-preserving operation."),
    ],
    pitfalls=[r"Importing the squaring counterexample ($x=-2$) - for cubes $(-2)^3 = -8 < 0$, so it does not apply.",
              r"Answering 'sufficient but not necessary' by pattern-matching to $x^2$ questions."],
    takeaway=r"Odd powers preserve sign and order; even powers do not. $x>0 \iff x^3>0$."),

"X2-25": Sol(
    idea=r"A quadratic inequality solved as if it were an equation-style 'both factors positive'. Find where the missing branch is lost.",
    steps=[
        (r"Lines I and II are fine: $x^2-5x+6 = (x-2)(x-3)$, so the inequality is $(x-2)(x-3)>0$.",
         r"Check: $-2\times-3 = 6$ and $-2-3=-5$ ✓."),
        (r"Line III says both factors must be positive. But a product is positive when both are positive **or** both are negative. **First error.**",
         r"Two negatives multiply to a positive - the case the student omits."),
        (r"The missing branch: $x-2<0$ and $x-3<0$, i.e. $x<2$.",
         r"Both factors negative requires the smaller bound."),
        (r"Full solution: $x<2$ or $x>3$. (Sketch check: the parabola is above the axis outside its roots.)",
         r"A quick sketch of an upward parabola confirms the two outer intervals."),
    ],
    pitfalls=[r"Blaming line IV - it correctly follows from line III's (incomplete) conditions.",
              r"Giving the answer as $2<x<3$, which is the solution of $<0$, not $>0$.",
              r"Solving factor-by-factor at all; sketching the parabola is faster and safer."],
    takeaway=r"$(x-p)(x-q)>0$ holds **outside** the roots, $<0$ **between** them. Sketch rather than case-split."),

"X2-26": Sol(
    idea=r"Extremal reasoning: squeeze $a$ and $c$ using the ordering, then test the remaining claim with an example.",
    steps=[
        (r"I: since $a<b<c$, we have $3a < a+b+c = 12$, so $a<4$, i.e. $a \leq 3$ for an integer. **True.**",
         r"Replacing $b$ and $c$ by the smallest value $a$ gives a strict under-estimate of the sum."),
        (r"II: similarly $3c > a+b+c = 12$, so $c>4$, i.e. $c \geq 5$. **True.**",
         r"Replacing $a$ and $b$ by the largest value $c$ over-estimates the sum."),
        (r"III: must $b=4$? Try $1+2+9 = 12$ with $1<2<9$ ✓ and $b=2$. **False.**",
         r"One valid triple with $b \neq 4$ settles it."),
        (r"So I and II.",
         r"Match to the list."),
    ],
    pitfalls=[r"Writing $3a \leq 12$ instead of $3a<12$; the strict ordering $a<b<c$ gives a strict inequality, though here both routes end at $a \leq 3$.",
              r"Assuming $b$ must be the mean of the three - true only for equally spaced values."],
    takeaway=r"Bound an ordered sum by replacing every term with the smallest (or largest): $3a < a+b+c < 3c$."),

"X2-27": Sol(
    idea=r"Same 'which is a valid proof' pattern as PRF-01: general argument versus cases, irrelevance and incompleteness.",
    steps=[
        (r"The valid proof: $n^2+n = n(n+1)$ is a product of consecutive integers, hence even; adding $1$ gives an odd number.",
         r"General, covering every positive integer with no case split."),
        (r"Checking $n=1,2,3$ gives $3,7,13$ - evidence, not proof.",
         r"Three cases out of infinitely many."),
        (r"'It cannot be factorised, so it is odd' - factorisability has nothing to do with parity ($6 = 2\times3$ and $9=3\times3$ are respectively even and odd).",
         r"An irrelevant premise cannot support the conclusion."),
        (r"'If $n$ is odd then ... so $n^2+n+1$ is odd' - correct but only for odd $n$; even $n$ is untreated. Incomplete.",
         r"A case-based proof must cover every case."),
        (r"'Suppose $n^2+n+1$ is even. Then $n$ is even, contradiction' - $n$ being even is not a contradiction; $n$ can be even.",
         r"A contradiction proof must actually reach an impossibility."),
    ],
    pitfalls=[r"Accepting the odd-$n$ argument because every line in it is true - truth is not completeness.",
              r"Accepting the contradiction attempt because it uses the right vocabulary."],
    takeaway=r"$n(n+1)$ is always even, so $n^2+n+1$ is always odd. A proof must be general, relevant and complete."),

"X2-28": Sol(
    idea=r"Extremal reasoning with **distinct integers**: the distinctness forces gaps of at least $1$ on each side of the median.",
    steps=[
        (r"Order the five values. The median (third value) is $10$.",
         r"Five values means the middle one is the third."),
        (r"The two above are distinct integers greater than $10$, so at least $11$ and $12$. Hence the largest is $\geq 12$. **I true.**",
         r"Distinct integers above $10$ must be $11$ or more, and two of them cannot both be $11$."),
        (r"Symmetrically, the two below are at most $9$ and $8$, so the smallest is $\leq 8$. **II true.**",
         r"Same argument downwards."),
        (r"Range $\geq 12-8 = 4$. **III true.**",
         r"Combining the two bounds. (The mean being $10$ is consistent - e.g. $8,9,10,11,12$ - but is not needed for any of the three claims.)"),
        (r"So all three.",
         r"Match to the list."),
    ],
    pitfalls=[r"Forgetting 'distinct' and allowing two values equal to $11$, which would break I.",
              r"Assuming the mean condition must be used; here it is extra information."],
    takeaway=r"Distinct integers force minimum gaps: $k$ values above a median $m$ reach at least $m+k$."),

"X2-29": Sol(
    idea=r"Volume and surface area are independent quantities. Neither condition constrains the other, so test both directions.",
    steps=[
        (r"Not sufficient: take a cube of side $1$ (volume $1$, surface $6$) and a cylinder of volume $1$ that is long and thin - say radius $0.1$, height $\frac{1}{0.01\pi} \approx 31.8$, whose surface area is far larger than $6$.",
         r"Equal volumes with wildly different shapes give wildly different surface areas."),
        (r"Not necessary: two solids can share a surface area while having different volumes, by the same flexibility of shape.",
         r"Stretching a cylinder thin at fixed surface area shrinks its volume."),
        (r"So $P$ is neither necessary nor sufficient for $Q$.",
         r"Match to the list."),
    ],
    pitfalls=[r"Assuming 'bigger volume means bigger surface area' - among different shapes, no such rule holds.",
              r"Testing only one direction and then guessing the other."],
    takeaway=r"Volume and surface area are independent across shapes; a sphere minimises surface area for a given volume, and everything else can be made worse without limit."),

"X2-30": Sol(
    idea=r"'Sufficient' means the condition alone guarantees the conclusion. Translate into the discriminant and check each option **guarantees** positivity.",
    steps=[
        (r"Two distinct real roots requires discriminant $b^2-4c>0$ (strictly).",
         r"Zero discriminant gives a repeated root, not two distinct ones."),
        (r"If $c<0$ then $-4c>0$, so $b^2-4c \geq -4c > 0$. **Guaranteed** - sufficient.",
         r"$b^2 \geq 0$ whatever $b$ is, so the whole expression is positive."),
        (r"$b^2 \geq 4c$ allows equality, which gives a repeated root - not sufficient for **distinct** roots.",
         r"Read the word 'distinct'; the boundary case ruins it."),
        (r"$b \neq 0$, $c>0$, $b>0$ give no control: e.g. $b=1, c=1$ has discriminant $-3<0$, no real roots.",
         r"One failing example shows a condition is not sufficient."),
    ],
    pitfalls=[r"Choosing $b^2 \geq 4c$ because it looks like the discriminant condition - it is the condition for **at least one** real root.",
              r"Confusing 'sufficient' with 'necessary': $c<0$ is not necessary ($x^2-5x+6$ has two distinct roots with $c=6$)."],
    takeaway=r"Distinct real roots $\iff b^2-4c>0$. A sufficient condition must force that strictly, with no exceptions."),

}
