"""Full teaching solutions: chains of reasoning (RSN-xx)."""
from gen.model import Sol

SOLUTIONS = {

"RSN-01": Sol(
    idea=r"A pigeonhole question. Build the 'boxes' so that two items in one box give exactly what you want, then answer boxes $+\,1$.",
    steps=[
        (r"Pair the numbers so that each pair differs by $10$: $\{1,11\}, \{2,12\}, \ldots, \{10,20\}$.",
         r"Every number from $1$ to $20$ lies in exactly one pair, and two numbers differ by $10$ precisely when they share a pair."),
        (r"There are $10$ pairs, so $10$ numbers can be chosen with no two in the same pair - for example $1$ to $10$.",
         r"This shows $10$ is **not** enough, which is the half of the argument people skip."),
        (r"With $11$ numbers and only $10$ pairs, two must come from the same pair - and those differ by $10$.",
         r"Pigeonhole: more items than boxes forces a repeat."),
        (r"So the smallest guaranteed $n$ is $11$.",
         r"Boxes $+ 1$."),
    ],
    pitfalls=[r"Answering $10$ - the largest selection that can **avoid** the condition, not the smallest that forces it.",
              r"Answering $2$, confusing 'could happen' with 'guaranteed'.",
              r"Forgetting to show $10$ is achievable; without it you have not proved $11$ is smallest."],
    takeaway=r"'Smallest $n$ that guarantees' $=$ (largest bad selection) $+\ 1$. Construct the boxes so a shared box means success."),

"RSN-02": Sol(
    idea=r"Three claims about integers constrained by a sum and a product. Sign analysis, an algebraic identity, and a prime-divisibility fact.",
    steps=[
        (r"I: $abc = 12 > 0$, so the number of negatives is even: $0$ or $2$. If none were negative, three positives could not sum to $0$. So exactly two are negative and one positive. **True.**",
         r"A positive product means an even count of negative factors; note $0$ is impossible since $abc \neq 0$."),
        (r"II: use $(a+b+c)^2 = a^2+b^2+c^2 + 2(ab+bc+ca)$. With $a+b+c=0$, $a^2+b^2+c^2 = -2(ab+bc+ca)$.",
         r"The identity converts a sum of squares into twice an integer."),
        (r"That is $2 \times$ an integer, hence **even**. **True.**",
         r"$ab+bc+ca$ is an integer because $a,b,c$ are."),
        (r"III: $3$ is prime and $3 \mid 12 = abc$, so $3$ divides one of the factors. **True.**",
         r"Euclid's lemma: a prime dividing a product divides one of the factors. This would fail for a composite like $4$."),
        (r"So all three. (Check with $-1, -3, 4$: sum $0$ ✓, product $12$ ✓.)",
         r"A concrete example confirms the constraints are satisfiable at all."),
    ],
    pitfalls=[r"Assuming exactly one negative because the product is positive - that would make the product negative.",
              r"Trying to settle II by testing examples rather than using the identity.",
              r"Thinking III needs a specific example; it follows from primality alone."],
    takeaway=r"$a+b+c=0$ makes $a^2+b^2+c^2 = -2(ab+bc+ca)$; and a prime dividing a product must divide a factor."),

"RSN-03": Sol(
    idea=r"A handshake (graph) consistency question. Test each list for an internal contradiction.",
    steps=[
        (r"Take $4,4,4,4,1$: four people each shook hands with all four others.",
         r"With five people, the maximum possible is $4$ handshakes each."),
        (r"If person $A$ shook hands with everyone, that includes the fifth person. The same for the other three.",
         r"Each of the four 'maximum' people contributes one handshake to the fifth person."),
        (r"So the fifth person made at least $4$ handshakes, not $1$. **Impossible.**",
         r"The list contradicts itself."),
        (r"The others are all realisable: $2,2,2,2,2$ is a pentagon; $4,4,4,4,4$ is everyone with everyone; $1,1,2,2,2$ is a chain $A$-$B$-$C$-$D$-$E$; and $0$ for one person just leaves them out.",
         r"Constructing one arrangement is enough to show a list is possible."),
    ],
    pitfalls=[r"Rejecting 'everyone shakes four hands' as too many - it is exactly the complete case and is fine.",
              r"Rejecting the list $1,1,2,2,2$ without trying to build it; a chain works.",
              r"Forgetting the parity check: the degree total must be even. $4+4+4+4+1 = 17$ is odd, which is a second, instant reason it is impossible."],
    takeaway=r"Two fast checks on a handshake list: the total must be even, and someone shaking everyone's hand forces everyone else's count up."),

"RSN-04": Sol(
    idea=r"A difference of two squares turns a quadratic condition into a factor-pair search.",
    steps=[
        (r"Factorise: $x^2 - y^2 = (x-y)(x+y) = 45$.",
         r"Difference of two squares converts the equation into a product of two integers."),
        (r"Both factors are positive with $x - y < x + y$, so list factor pairs of $45$ with the smaller first: $(1,45), (3,15), (5,9)$.",
         r"$x, y$ positive forces $x + y > 0$, and then $x - y > 0$ too since the product is positive."),
        (r"Solve each: $x = \frac{\text{sum}}{2}$, $y = \frac{\text{difference}}{2}$, giving $(23,22), (9,6), (7,2)$.",
         r"Adding the two equations gives $2x$; subtracting gives $2y$. Both factors are odd, so both results are integers."),
        (r"All three have positive integer $y$, so there are **three** pairs.",
         r"Check one: $9^2 - 6^2 = 81-36 = 45$ ✓."),
    ],
    pitfalls=[r"Including $(9,5)$ or other reversed pairs - $x-y$ must be the smaller factor.",
              r"Forgetting to check that $x$ and $y$ come out as integers; if $45$ had a factor pair of mixed parity it would have to be discarded.",
              r"Counting $45 = 45 \times 1$ and $1 \times 45$ as two different solutions."],
    takeaway=r"$x^2-y^2 = N$: list factor pairs $N = de$ with $d<e$ and the same parity, then $x = \frac{d+e}2$, $y = \frac{e-d}2$."),

"RSN-05": Sol(
    idea=r"An invariant argument: count what each match achieves rather than simulating the draw.",
    steps=[
        (r"At the end one player remains, so $37 - 1 = 36$ players have been eliminated.",
         r"Count the outcome, not the structure."),
        (r"Each match eliminates exactly **one** player.",
         r"Given in the question - this is the invariant."),
        (r"So the number of matches equals the number of eliminations: $36$.",
         r"And this holds whatever byes or bracket shape are used, which is why the answer is unique."),
    ],
    pitfalls=[r"Trying to build the bracket and getting lost in byes because $37$ is not a power of $2$.",
              r"Halving repeatedly ($18, 19$-type answers), which only works for tidy brackets."],
    takeaway=r"Count the invariant: a knockout with $n$ players always takes $n-1$ matches."),

"RSN-06": Sol(
    idea=r"Test each candidate against all three statements and count how many are true. You want the one that does **not** give exactly two.",
    steps=[
        (r"$36$: perfect square ($6^2$) ✓, multiple of $6$ ✓, less than $50$ ✓ - **three** true.",
         r"The condition demands exactly two, so $36$ is ruled out."),
        (r"$16$: square ✓, multiple of $6$ ✗, $<50$ ✓ - two. Allowed.",
         r"Check each of the three statements, do not stop early."),
        (r"$25$: square ✓, multiple of $6$ ✗, $<50$ ✓ - two. $48$: square ✗, multiple of $6$ ✓, $<50$ ✓ - two. $12$: the same pattern - two.",
         r"All fine."),
        (r"$144$: square ($12^2$) ✓, multiple of $6$ ✓, $<50$ ✗ - two. Allowed.",
         r"So only $36$ fails."),
    ],
    pitfalls=[r"Reading 'exactly two are true' as 'at least two', which would admit $36$.",
              r"Missing that $144 = 12^2$ is both a square and a multiple of $6$.",
              r"Looking for the value making the fewest statements true instead of the most."],
    takeaway=r"'Exactly $k$' excludes $k+1$ as firmly as $k-1$; tabulate every statement for every candidate."),

"RSN-07": Sol(
    idea=r"Count the same total two different ways - the standard double-counting move.",
    steps=[
        (r"The three rows between them contain each digit $1$ to $9$ exactly once.",
         r"Every cell lies in exactly one row, so the rows partition the grid."),
        (r"So the three row sums add to $1+2+\cdots+9 = 45$.",
         r"Use $\frac{9 \times 10}{2} = 45$."),
        (r"All three row sums are equal, so each is $\frac{45}{3} = 15$.",
         r"And the columns give the same total, so they must each be $15$ too - consistent."),
    ],
    pitfalls=[r"Answering $45$, the grand total rather than one row's sum.",
              r"Trying to construct an actual magic square; the total settles it with no construction needed."],
    takeaway=r"Double-count a total: rows partition the grid, so (number of rows) $\times$ (row sum) $=$ grand total."),

"RSN-08": Sol(
    idea=r"Inequality manipulation with 'must be true'. Two follow from replacing a term by a larger one; the third involves multiplying, which needs sign information.",
    steps=[
        (r"I: from $a < c$ and $b < c$, add: $a + b < 2c$. **True.**",
         r"Adding two inequalities of the same direction is always valid."),
        (r"III: $a < c$ so $a + c < 2c$, and dividing by $2$ gives $\frac{a+c}{2} < c$. **True.**",
         r"Dividing by a positive constant preserves the direction. (The midpoint of two numbers lies below the larger.)"),
        (r"II: $ab < bc$ would follow from $a<c$ only if we could multiply by $b$ - valid only for $b > 0$.",
         r"Multiplying an inequality by a negative number reverses it."),
        (r"Counterexample: $a=-3, b=-2, c=-1$ satisfies $a<b<c$, but $ab = 6$ and $bc = 2$, so $ab > bc$. **False.**",
         r"All-negative values are the natural place to test a multiplication claim."),
        (r"So I and III.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting II by 'multiplying $a<c$ by $b$' without checking the sign of $b$.",
              r"Testing only positive numbers, where II does hold."],
    takeaway=r"Adding inequalities is always safe; multiplying by a variable is not - you need its sign."),

"RSN-09": Sol(
    idea=r"Turn a two-variable Diophantine equation into a product by the 'add a constant and factorise' trick.",
    steps=[
        (r"Set up: $ab = 2a + 2b$ with $a,b$ positive integers.",
         r"Area equals perimeter, numerically."),
        (r"Rearrange: $ab - 2a - 2b = 0$, then add $4$ to both sides: $ab - 2a - 2b + 4 = 4$.",
         r"The added constant is the product of the two subtracted coefficients, chosen to make the left side factorise."),
        (r"Factorise: $(a-2)(b-2) = 4$.",
         r"Check by expanding: $ab - 2a - 2b + 4$ ✓."),
        (r"Positive factor pairs of $4$ with $a-2 \leq b-2$: $(1,4)$ and $(2,2)$, giving $3\times 6$ and $4 \times 4$.",
         r"Negative factors would need $a < 2$; $a = 1$ gives $b - 2 = -4$, i.e. $b = -2$, not a length."),
        (r"So **two** rectangles.",
         r"Check: $3\times6$ has area $18$ and perimeter $18$ ✓; $4\times4$ has $16$ and $16$ ✓."),
    ],
    pitfalls=[r"Counting $3\times 6$ and $6\times 3$ separately - the question says to count each rectangle once.",
              r"Forgetting to add $4$ and being unable to factorise.",
              r"Including the factor pair $(4,1)$ as a third solution."],
    takeaway=r"$ab + pa + qb = r$ factorises after adding $pq$: $(a+q)(b+p) = r + pq$. Then list factor pairs."),

"RSN-10": Sol(
    idea=r"Pigeonhole again, with the pairs built to sum to the target.",
    steps=[
        (r"Pair the numbers to sum to $101$: $\{1,100\}, \{2,99\}, \ldots, \{50,51\}$.",
         r"Each of $1$ to $100$ lies in exactly one such pair, so there are $50$ pairs."),
        (r"Drawing one card from each pair gives $50$ cards with **no** pair summing to $101$ - for example $1$ to $50$.",
         r"So $50$ is not enough; this constructs the worst case."),
        (r"Any $51$ cards must include two from one pair, and those sum to $101$.",
         r"$51$ cards into $50$ pairs forces a repeat."),
    ],
    pitfalls=[r"Answering $50$ - the largest number that can fail.",
              r"Answering $2$ by thinking about luck rather than certainty."],
    takeaway=r"Same recipe as any pigeonhole guarantee: build the pairs, show the worst case, then add one."),

"RSN-11": Sol(
    idea=r"Three consecutive integers: automatic divisibility by $2$ and $3$, but not by $4$; plus a neat algebraic identity.",
    steps=[
        (r"Write the three as $m-1, m, m+1$, so $N = (m-1)m(m+1)$.",
         r"Centring on the middle term is what makes III come out."),
        (r"I: among any three consecutive integers there is at least one multiple of $2$ and one multiple of $3$, so $6 \mid N$. **True.**",
         r"Every second integer is even and every third is a multiple of $3$."),
        (r"II: test the smallest case $1 \times 2 \times 3 = 6$, which is not divisible by $4$. **False.**",
         r"Three consecutive integers contain only one or two evens; when only one, it may contribute a single factor of $2$."),
        (r"III: $N + m = (m^2-1)m + m = m^3 - m + m = m^3$ - a perfect cube. **True.**",
         r"$(m-1)(m+1) = m^2-1$ is the difference of squares; the $-m$ and $+m$ cancel."),
        (r"So I and III.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting II by testing $2\times3\times4 = 24$ only - one confirming case is not enough.",
              r"Expanding $N$ the long way instead of using $(m-1)(m+1) = m^2-1$."],
    takeaway=r"$k$ consecutive integers are always divisible by $k!$ - here $3! = 6$, but not necessarily by $4$."),

"RSN-12": Sol(
    idea=r"Inclusion-exclusion: count what you don't want and subtract. Take care with 'less than $1000$'.",
    steps=[
        (r"The range is $1$ to $999$, so $999$ integers.",
         r"'Less than $1000$' excludes $1000$ itself."),
        (r"Multiples of $2$: $\left\lfloor \frac{999}{2}\right\rfloor = 499$. Multiples of $5$: $199$. Multiples of both, i.e. of $10$: $99$.",
         r"Divide and round down. $10$ is the LCM of $2$ and $5$."),
        (r"Divisible by $2$ or $5$: $499 + 199 - 99 = 599$.",
         r"Subtract the overlap, which was counted twice."),
        (r"Neither: $999 - 599 = 400$.",
         r"Sanity check: in each block of $10$ consecutive integers exactly $4$ (ending in $1,3,7,9$) survive, and $999 = 99$ full blocks plus $991$-$999$, giving $99 \times 4 + 4 = 400$ ✓."),
    ],
    pitfalls=[r"Using $1000$ as the count and getting $400$ by luck with wrong intermediate figures - or getting $399$ by an off-by-one at the top.",
              r"Forgetting to subtract the multiples of $10$, giving $999 - 698 = 301$."],
    takeaway=r"$|A \cup B| = |A| + |B| - |A \cap B|$, with the intersection counted via the LCM; then subtract from the total."),

"RSN-13": Sol(
    idea=r"Parity applied to primes: the sum of two primes is odd only if one of them is $2$.",
    steps=[
        (r"$45$ is odd, so one prime is even and one odd.",
         r"odd $+$ odd $=$ even, even $+$ even $=$ even; only odd $+$ even gives an odd total."),
        (r"The only even prime is $2$, so $p = 2$ and $q = 43$.",
         r"$2$ is the unique even prime - every other even number has $2$ as a proper factor."),
        (r"Check $43$ is prime: not divisible by $2, 3, 5$ and $7^2 = 49 > 43$, so yes.",
         r"Test primes up to the square root only."),
        (r"$pq = 2 \times 43 = 86$.",
         r"The question asks for the product, not the primes."),
    ],
    pitfalls=[r"Trying odd pairs like $2+43$ versus $5+40$ at random; $40$ is not prime and no odd pair can work at all.",
              r"Answering $43$ or $45$ instead of the product."],
    takeaway=r"An odd sum of two primes forces one of them to be $2$. Parity settles most prime puzzles instantly."),

"RSN-14": Sol(
    idea=r"The addition rule, with 'every student studies at least one' supplying the missing total.",
    steps=[
        (r"'At least one of Maths and Physics' means $P(M \text{ or } P) = 1$.",
         r"Nobody is outside the union, so the union has probability $1$."),
        (r"Apply the addition rule: $P(M \cup P) = P(M) + P(P) - P(M \cap P)$.",
         r"Subtract the overlap, which the two percentages each count."),
        (r"Substitute: $1 = 0.7 + 0.6 - P(\text{both})$, so $P(\text{both}) = 1.3 - 1 = 0.3$.",
         r"The excess of $1.3$ over $1$ is exactly the double-counted overlap."),
    ],
    pitfalls=[r"Multiplying $0.7 \times 0.6 = 0.42$ by assuming independence - nothing here says the subjects are independent, and the union condition rules it out.",
              r"Answering 'cannot be determined'; the 'at least one' condition is precisely what makes it determinable."],
    takeaway=r"When percentages sum to more than $100\%$ and everyone is covered, the excess **is** the overlap."),

"RSN-15": Sol(
    idea=r"Group the terms into blocks that the given conditions control, then read off each claim.",
    steps=[
        (r"I: split the ten terms into terms $1$-$5$ and terms $6$-$10$ - two blocks of five consecutive terms.",
         r"Each block has negative sum by hypothesis, and the two blocks together are the whole sequence."),
        (r"Negative $+$ negative $=$ negative, so the total is negative. **True.**",
         r"The grouping is exact - no term is used twice or left out."),
        (r"II: terms $1$-$5$ sum to a negative number, so at least one of them is negative (five non-negative terms could not). **True.**",
         r"A sum is negative only if some summand is."),
        (r"III: terms $1$-$3$ sum to a positive number, so at least one is positive. **True.**",
         r"Same argument the other way round."),
        (r"So all three.",
         r"Match to the list. (Such sequences do exist for $10$ terms - the conditions become contradictory only for longer sequences.)"),
    ],
    pitfalls=[r"Trying to construct an explicit sequence; the claims follow from the block structure alone.",
              r"Thinking the sum of all ten is ambiguous because $10$ is not a multiple of $3$ - use the blocks of five, which do fit."],
    takeaway=r"Partition the sequence into blocks the hypotheses control; a negative sum forces a negative term, a positive sum a positive one."),

"RSN-16": Sol(
    idea=r"Represent the numbers symmetrically about the middle so everything cancels, then read off the guaranteed factor.",
    steps=[
        (r"Let the middle number be $m$ (odd). The five are $m-4, m-2, m, m+2, m+4$.",
         r"Consecutive odd numbers differ by $2$; centring makes the offsets cancel in pairs."),
        (r"Add: the $\pm2$ and $\pm4$ cancel, leaving $S = 5m$.",
         r"So $5$ is always a factor."),
        (r"Is $10$ always a factor? $m$ is odd, so $5m$ is odd and never divisible by $2$. **No.**",
         r"For instance $1+3+5+7+9 = 25$."),
        (r"Are $3$, $15$ or $25$ always factors? $25$ needs $5 \mid m$, $3$ needs $3 \mid m$ - neither is guaranteed ($m = 7$ gives $S = 35$).",
         r"Only the factor $5$ survives every case."),
    ],
    pitfalls=[r"Answering $25$ from the single example $1+3+5+7+9 = 25$ - that is $5m$ with $m=5$, a coincidence.",
              r"Answering $10$ by assuming an even total; five odd numbers sum to an odd number."],
    takeaway=r"An odd count of equally spaced terms sums to (count) $\times$ (middle term). Test the extra factors against a second example."),

"RSN-17": Sol(
    idea=r"A truth-teller puzzle. Assume each person in turn is the sole truth-teller and check the whole scenario for consistency.",
    steps=[
        (r"Suppose **Alice** is truthful. Then Ben lies, so 'Cara is lying' is false, so Cara is truthful. That makes two truth-tellers - contradiction.",
         r"Exactly one truth-teller is the constraint; two breaks it."),
        (r"Suppose **Cara** is truthful. Then Alice and Ben both lie. But Alice lying means 'Ben is lying' is false, so Ben is truthful - contradiction.",
         r"Cara's own statement collapses under its consequences."),
        (r"Suppose **Ben** is truthful. Then Cara lies, so Ben is not lying ✓ consistent. Alice says 'Ben is lying', which is false, so Alice lies ✓. Cara says both Alice and Ben lie - false, since Ben is truthful ✓.",
         r"Every statement's truth value matches the assumed roles, with exactly one truth-teller."),
        (r"So Ben is the truth-teller.",
         r"Two cases eliminated, one consistent - the answer is determined."),
    ],
    pitfalls=[r"Stopping at the first scenario that seems to work without checking every statement.",
              r"Declaring the situation impossible after two failed cases instead of testing the third.",
              r"Forgetting that a liar's statement must come out **false**, which is itself information."],
    takeaway=r"Test each candidate exhaustively: a consistent assignment must satisfy every statement **and** the count of truth-tellers."),

"RSN-18": Sol(
    idea=r"Clear the fractions, then use the add-a-constant factorising trick and count **ordered** pairs.",
    steps=[
        (r"Multiply $\frac1m + \frac1n = \frac14$ by $4mn$: $4n + 4m = mn$.",
         r"Clearing denominators turns it into a polynomial equation in integers."),
        (r"Rearrange and factorise: $mn - 4m - 4n + 16 = 16$, so $(m-4)(n-4) = 16$.",
         r"Add $(-4)(-4) = 16$ to both sides to complete the rectangle."),
        (r"$m, n$ positive: if $m - 4$ were negative then $m \in \{1,2,3\}$ and $n-4 = \frac{16}{m-4}$ would make $n$ negative. So both factors are **positive**.",
         r"Check the negative branch explicitly rather than assuming; e.g. $m = 3$ gives $n - 4 = -16$, $n = -12$ ✗."),
        (r"Positive factor pairs of $16$: $(1,16),(2,8),(4,4),(8,2),(16,1)$ - **five** ordered pairs.",
         r"'Ordered' means $(m,n)$ and $(n,m)$ count separately: $(5,20), (6,12), (8,8), (12,6), (20,5)$."),
    ],
    pitfalls=[r"Answering $3$ by counting unordered pairs when the question says ordered.",
              r"Forgetting $(4,4)$, the square factor pair.",
              r"Including negative factor pairs without checking they give positive $m, n$."],
    takeaway=r"$\frac1m+\frac1n=\frac1k$ becomes $(m-k)(n-k) = k^2$; then count factor pairs, respecting ordered versus unordered."),

"RSN-19": Sol(
    idea=r"Two conditions, two unknowns: translate each sentence into an equation, then solve simultaneously.",
    steps=[
        (r"Let $r$ be red and $b$ blue. Removing one red: $r - 1 = \frac14(r + b - 1)$.",
         r"The total drops by $1$ as well as the red count - both sides of the fraction change."),
        (r"Removing two blues: $r = \frac13(r + b - 2)$.",
         r"Here the red count is unchanged; only the total falls, by $2$."),
        (r"From the second: $3r = r + b - 2$, so $b = 2r + 2$.",
         r"Solve the simpler equation first and substitute."),
        (r"Substitute into the first: $4(r-1) = r + (2r+2) - 1 = 3r + 1$, so $4r - 4 = 3r + 1$ and $r = 5$.",
         r"Multiply through by $4$ to clear the fraction before substituting."),
        (r"Then $b = 12$ and the total is $17$.",
         r"Check: remove one red $\to 4$ red of $16$ $= \frac14$ ✓; remove two blue $\to 5$ red of $15 = \frac13$ ✓."),
    ],
    pitfalls=[r"Forgetting that removing a ball also reduces the **total**, giving $r - 1 = \frac14(r+b)$.",
              r"Answering $r$ or $b$ rather than the total.",
              r"Not checking the answer against both original statements."],
    takeaway=r"When items are removed, adjust the total as well as the category; then verify against both conditions."),

"RSN-20": Sol(
    idea=r"Use the structure of the divisor count. Exactly three divisors is a very restrictive condition.",
    steps=[
        (r"A number with exactly $3$ divisors must be $p^2$ for a prime $p$: its divisors are $1, p, p^2$.",
         r"If a number had two distinct prime factors it would have at least $4$ divisors; $p^3$ has $4$; $p$ alone has $2$."),
        (r"So $n^2 = p^2$, and since both are positive, $n = p$.",
         r"Take the positive square root."),
        (r"Therefore $n$ is **prime**.",
         r"That is the only guaranteed property."),
        (r"Check the others: $n = 2$ is even, $n = 3$ is odd - so neither parity is forced; and $n$ prime is never a perfect square.",
         r"Both $n=2$ and $n=3$ satisfy the condition ($4$ and $9$ have three divisors each), which kills the parity options."),
    ],
    pitfalls=[r"Answering '$n$ is a perfect square' by confusing $n$ with $n^2$.",
              r"Answering $n = 3$ from one example; $n = 2, 5, 7$ all work too."],
    takeaway=r"Exactly $3$ divisors $\iff$ the square of a prime. Divisor counts come from the prime factorisation exponents."),

"RSN-21": Sol(
    idea=r"Seven consecutive integers: the sum telescopes about the middle, and the seven values cover all remainders mod $7$.",
    steps=[
        (r"Let the middle be $m$; the seven are $m-3, \ldots, m+3$, and the offsets cancel, so the sum is $7m$. **I is true.**",
         r"Symmetric representation makes the cancellation immediate."),
        (r"II: seven consecutive integers take all seven remainders on division by $7$, so exactly one is a multiple of $7$; hence $7$ divides the product. **True.**",
         r"Among any $k$ consecutive integers there is exactly one multiple of $k$."),
        (r"III: the sum is $7m$, which is odd only when $m$ is odd. Take $1,\ldots,7$: sum $28$, even. **Not always true.**",
         r"One counterexample settles it."),
        (r"So I and II.",
         r"Match to the list."),
    ],
    pitfalls=[r"Accepting III after testing $2,\ldots,8$ (sum $35$, odd) and no other case.",
              r"Confusing the sum and product claims - I is about $7m$, II about a multiple of $7$ among the factors."],
    takeaway=r"$k$ consecutive integers: their sum is $k \times$ middle (for odd $k$), and exactly one of them is a multiple of $k$."),

"RSN-22": Sol(
    idea=r"Count by rows - the column condition is extra information, not needed for the count.",
    steps=[
        (r"There are $4$ rows and each contains exactly $2$ black squares.",
         r"Every black square lies in exactly one row, so rows partition them."),
        (r"Total $= 4 \times 2 = 8$.",
         r"No double counting."),
        (r"Check with the columns: $4 \times 2 = 8$ as well - consistent, which is why such a colouring can exist.",
         r"If the two counts disagreed, no such grid would exist."),
    ],
    pitfalls=[r"Adding rows and columns to get $16$ - that counts every black square twice.",
              r"Answering $4$ by counting rows rather than squares."],
    takeaway=r"Count via one partition only; use the other as a consistency check, not as extra squares."),

}
